### ISSUE TITLE
Ethereum v2 market on kovan broken 

### ISSUE THREAD

**Issue by MareskoY** [aave/interface#1039]
Testnet kovan market for ethereum v2 broken 

there is some problem with rpc
``` POST https://eth-kovan.alchemyapi.io/v2/demo 503```

<img width="1496" alt="Screenshot 2022-08-19 at 12 05 05" src="https://user-images.githubusercontent.com/18032275/185605392-a0a91367-bb1c-458c-b011-c0a48ac026d3.png">

**Comment by bojanaave** [comment]
After discussion with @MareskoY  @0x4Graham  we can consider this ticket is verified , since we are planning to "kill" Kovan market soon.
![2](https://user-images.githubusercontent.com/104987757/186398791-8230f580-fa4a-4f09-b20f-e858629fe899.jpg)
