### ISSUE TITLE
Search field does not work inside "Wallet Connect" modal

### ISSUE THREAD

**Issue by bojanaave** [aave/interface#1049]
**Describe the bug**
Search input field does not work inside "Wallet Connect" modal
**To Reproduce**

1. Go to app.aave.com
2. Click on Connect wallet 
3. Click on the "Wallet Connect" option
4. Switch from QR code -> Desktop
5. Click on the Search field and try to enter some letters / words

**Expected behavior**
Search field should work

**Screenshots**

https://user-images.githubusercontent.com/104987757/185957475-61f4199a-47c8-4c30-8660-6a5f6cfcfef6.mov

**Desktop (please complete the following information):**

- macOS 
 - Chrome (latest)

**Comment by grothem** [comment]
This is an issue on the WalletConnect side. There's an issue raised here about it: https://github.com/WalletConnect/walletconnect-monorepo/issues/981
