### ISSUE TITLE
Show link to interest rate strategy

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#1081]
**Is your feature request related to a problem? Please describe.**
I want to check out which interest rate a reserve is using.
While I can check 
![image](https://user-images.githubusercontent.com/4396533/187879111-11324062-64d3-4aca-8068-3fded7d7f500.png)
This picture is "incomplete" as it e.g. will not show stable parameters when stable rate is not enabled.

**Describe the solution you'd like**
Like with token addresses it would be good to have a link to the strategy on the ui, so ppl can check it out. It's very cumbersome to find the address, but the ui already has it.

**Comment by 0x4Graham** [comment]
@sakulstra 

Why would you want to show stable rate on the graph? I think by showing it on the graph when it is not enabled will be confusing and not required. 

Are you talking about the variableDebtToken address for an asset? Or the interest rate strategy? 

The variable debt token address can be found at the top of the page: 
![image](https://user-images.githubusercontent.com/7548837/187905108-fdfced9b-2887-41fe-b1a2-5cb38a8e50f5.png)

**Comment by sakulstra** [comment]
@0x4Graham perhaps my message was confusing. I don't want to show stable rate on the graph - i did these graphs:)
Was writing stable rate because it's obviously missing here (because it's disabled).

The interest rate curve has some specific configurations that are not shown in the ui (e.g. excess factors), having the address is useful for ppl interested in the details and teams listing new assets as they can easily compare existing curves.

https://polygonscan.com/address/0x41B66b4b6b4c9dab039d96528D1b88f7BAF8C5A4#readContract as you can see here there are far more parametres then shown on the ui.

**Comment by defispartan** [comment]
This would be a good addition, and it's an easy add :)

**Comment by defispartan** [comment]
Merged in #1102
