### ISSUE TITLE
Wrong assets on Avalanche V3

### ISSUE THREAD

**Issue by MareskoY** [aave/interface#1101]
There are 2 assets which is related to Polygon V3 but showing on avalanche V3 market

<img width="1397" alt="Screenshot 2022-09-07 at 16 42 31" src="https://user-images.githubusercontent.com/18032275/188921282-91252649-9d2e-4c9d-ad57-d4e35251750c.png">

at the same time FRAX on polygon is not available but should be

**Comment by defispartan** [comment]
MAI and FRAX are reserved on the Avalanche V3 market as well.

As for FRAX not being listed on Polygon, this will appear on the UI only if this reserve is added by the community guardians.
