### ISSUE TITLE
Health Factor is showing as a negative number in some cases in repay modal

### ISSUE THREAD

**Issue by grothem** [aave/interface#1104]
**Describe the bug**
In the repay modal, the future health factor number is calculated as a negative number in some cases, which is confusing in the UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/23554636/189179101-14c7744b-3933-4643-82e7-35ae6a81e9f6.png)

**Additional context**
There was a similar issue with the remaining debt value showing as negative. That was fixed by setting it to 0 if it was negative, so a similar fix might be needed here.

This issue probably exists in both the repay with wallet balance and the repay with collateral modals, so the fix might have to be applied in both spots (if that logic isn't shared already)

**Comment by lyzergic** [comment]
[PR](https://github.com/aave/interface/pull/1695)
