### ISSUE TITLE
Ethereum market ETH asset links to WETH

### ISSUE THREAD

**Issue by drewcook** [aave/interface#1151]
**Describe the bug**
A clear and concise description of what the bug is, including the exact market(e.g. polygon v3) on which it was observed.

When viewing Ethereum v2 markets, clicking the list item for ETH asset links to the reserve overview page for WETH, not ETH.  This can cause confusion.  WETH is used on all all v3 networks, since they are all non-Ethereum L1s and Ethereum L2s and don't contain the native asset, which is accurate.  However, the the Ethereum v2 markets should be showing data for the native asset, not the wrapped one.

**To Reproduce**

1. Go to https://app.aave.com/markets/ or https://app.aave.com
2. Select a v2 Ethereum market
3. Click on 'Details' button for ETH
4. See issue that WETH details are used/shown

**Expected behavior**

The underlying asset should be ETH.  If, in fact, the correct UUID _is_ being used, then the appropriate display names/icons should be shown for ETH, no WETH.

**Comment by defispartan** [comment]
New design in progress, the proposed flow is:

- Only show the wrapped base asset on markets page (as this is the reserve token)
- Show wrapped and un-wrapped on "Assets to supply" and "Assets to borrow" sections on dashboard

**Comment by 0x4Graham** [comment]
Closing as it was shippep
