### ISSUE TITLE
Dashboard block borrow in limit of debt (USDt)

### ISSUE THREAD

**Issue by MareskoY** [aave/interface#1154]
for now if debt limit is max we don't display asset(with debt limit) on borrow dashboard 

Case: 
- Avalanche market v3
- there is some deposit 

result: 
- on the borrow dashboard view USDt is hidden - that's wrong
![Screenshot 2022-09-19 at 13 18 53](https://user-images.githubusercontent.com/18032275/191015538-89d76d3a-cb6b-4ac6-91a6-1e3a6776a0f0.png)

- but borrow is still available on the Asset page and on borrowed row 
<img width="701" alt="Screenshot 2022-09-19 at 13 19 10" src="https://user-images.githubusercontent.com/18032275/191015592-3b9675b7-dc45-4a2a-9247-7fbb7977a16d.png">

Should be:
- borrow of USDt should be available

**Comment by defispartan** [comment]
Closed by #1426
