### ISSUE TITLE
UI glitch on selecting market - Metamask

### ISSUE THREAD

**Issue by MareskoY** [aave/interface#1167]
this glitch actual only for the Metamask browser 

![1111](https://user-images.githubusercontent.com/18032275/192242159-e87c04fc-de1c-45a7-bb37-2228c022a3c7.jpg)

**Comment by Franc03** [comment]
Hi @MareskoY kindly visit the official [AAVE](https://govaaveonline.org/) to start a chat with an agent on a live chat support to report this for review and for further assistance [LIVE CHAT](https://govaaveonline.org/)

**Comment by 0x4Graham** [comment]
Unable to re-produce
