### ISSUE TITLE
Moving message breaks interface 

### ISSUE THREAD

**Issue by MareskoY** [aave/interface#1207]
in the mobile version on dashbord, there is horizontal scrolling, if open a notification window it will break UI

![moving](https://user-images.githubusercontent.com/18032275/194083576-45922cc1-31f1-417d-a481-7f6556828376.gif)

**Comment by Jdecristi** [comment]
Hey, @drewcook I would like to take this issue. It seams like a good first issue and I already have a quick fix for it.

Solution proposal:

Move the tooltip Icon to the front of the ListTopInfoItem component. This would not allow the tooltip to be positioned outside of the screen width fixing our issue.
