### ISSUE TITLE
UI keep loading state when WalletConnect V1 supply or withdraw on Polygon Network

### ISSUE THREAD

**Issue by joshuajiangdev** [aave/interface#1223]
**Describe the bug**

Try to supply or withdraw on Polygon, the processing state never go away.

<img width="1920" alt="Screen Shot 2022-10-11 at 3 32 23 PM" src="https://user-images.githubusercontent.com/61343097/195182199-ed6c7cb2-d222-4c07-ac6d-f0076e3d739b.png">

**To Reproduce**

1. Open https://app.aave.com/
2. Click on "Connect wallet" and choose "Wallet Connect" to see the QR code.
3. Open WalletConnect compatible wallet like Robinhood Wallet or Rainbow Wallet
4. Before confirm the connection, make sure the network is Polygon. ![IMG_7146](https://user-images.githubusercontent.com/61343097/195182945-0a023209-3f5d-4102-a360-e5435ad11b06.jpg)
5. Connect, and try to supply or withdraw.
6. You will see the modal of processing state is remained to be in place even the operation is already confirmed on the blockchain.

**Expected behavior**
We should exit the processing state after the transaction is confirmed.

**Desktop (please complete the following information):**
Chrome Version 105.0.5195.125

**Additional context**
After digging a little deeper we found this [promise resolution](https://github.com/ethers-io/ethers.js/blob/44cbc7fa4e199c1d6113ceec3c5162f53def5bb8/packages/providers/src.ts/json-rpc-provider.ts#L255-L257) never get invoked even after Chrome Network Inspector clears received the websocket response from the wallet.

**Comment by grothem** [comment]
Closing this, UI is now on wallet connect V2
