### ISSUE TITLE
APY don't match for negative return when Stablecoin E-mode activated

### ISSUE THREAD

**Issue by NandyBa** [aave/interface#1242]
**Bug describtion**
APY calculation seems wrong when return are negative and e-mode stablecoin activated. In fact it seems overestimated.

**To Reproduce**
At this time :

1. Deposit USDC on Polygon
2. Activate E-mode stablecoin
3. Borrow jEUR near borrow limit

Alternative:
1. deposit EURS
2. Activate E-mode stablecoin
3. Borrow USDC near borrow limit

**Expected behavior**
APY take into account E-mode

**Screenshots**
![Capture d’écran 2022-10-13 à 20 43 06](https://user-images.githubusercontent.com/11545946/195683573-81a3fa67-ac53-4625-b6eb-d6e70b90280e.png)
![Capture d’écran 2022-10-13 à 21 04 06](https://user-images.githubusercontent.com/11545946/195686449-5e7a0462-6f32-415a-b5a9-5b703125112c.png)

**Comment by defispartan** [comment]
Net APY is the net effect of supply and borrow interest relative to net worth

In the first screenshot you can calculate as:

Net APY = (supply interest - borrow interest) / net worth
	= ((2187.32 * 0.0118) - (2073 * 0.0265)) / 114
	= (25.8 - 54.93) / 114
	= -.25 = -25%
