### ISSUE TITLE
Text (links) goes out of box over mobile on active proposals 

### ISSUE THREAD

**Issue by bojanaave** [aave/interface#1260]
Environment: [app.aave.com/governance](http://app.aave.com/governance) 
Browser/OS: iOS /  Chrome simulator
Reproduction steps:
1. Open link above (over mobile / or over (chrome simulator) 
2. Open Active Proposal “Whitelist Balancer’s Liquidity Mining Claim” 
3. Scroll down the page 
4. Observe
Actual:
Some URLs goes out of box 

Video : on Notion

**Comment by grothem** [comment]
Closing this, doesn't seem to be an issue anymore
