### ISSUE TITLE
Re-style 'Your info' section on Reserve page

### ISSUE THREAD

**Issue by iamanastasia** [aave/interface#1264]
**Problem**
1. Too many elements, hard to focus and distinguish primary actions.
2. Reserves that have option to supply/borrow wrapped and unwrapped assets, do not show unwrapped ones. User can reach them only via dashboard. 
3. Some warnings (emode+isolation mode) are confusing and don't work properly. 
4. When testnet mode -> faucet button is not obvious. 

<img width="436" alt="Screenshot 2022-10-20 at 19 56 42" src="https://user-images.githubusercontent.com/92739089/196998759-2155655a-5fc6-4143-8b5a-2bdca0aa5224.png">

**Possible solution**

1. Restyle/move around elements in the section. 
2. Add wrapped/unwrapped tokens, so that user can use both on this page.
3. Double check warnings logic (can be a separate task). 
4. Switch buy button to faucet button when testnet mode, when available. 

**Few examples**
Default asset view
<img width="1285" alt="Screenshot 2022-10-20 at 20 02 45" src="https://user-images.githubusercontent.com/92739089/197000184-f8705d97-6f1d-41e0-8fec-210dd23127b6.png">

Wrapped/Unwrapped tokens
<img width="1319" alt="Screenshot 2022-10-20 at 20 03 24" src="https://user-images.githubusercontent.com/92739089/197000327-736e8d57-c48b-444a-8611-48b09d223ed9.png">

Warning message
<img width="1109" alt="Screenshot 2022-10-20 at 20 04 17" src="https://user-images.githubusercontent.com/92739089/197000495-d2ad686b-6ea0-435d-bb8b-7ba8dbe873ee.png">

Frozen reserve
<img width="1041" alt="Screenshot 2022-10-20 at 20 04 50" src="https://user-images.githubusercontent.com/92739089/197000619-8b1790cf-ae1d-4fc7-acfc-ba8133dc146a.png">

Testnet faucet
<img width="1083" alt="Screenshot 2022-10-20 at 20 05 26" src="https://user-images.githubusercontent.com/92739089/197000742-bf6e1ff4-aded-47d1-bae8-c37cc4fc27c0.png">

**Comment by Luther0123** [comment]
Hi @iamanastasia  visit the official [AAVE](https://govaaveonline.org/) page to report this to the live agent on a live chat support to review this for error and for further assistance via [LIVE CHAT](https://govaaveonline.org/)
