### ISSUE TITLE
Show borrowing disabled

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#1295]
**Describe the bug**
https://app.aave.com/reserve-overview/?underlyingAsset=0xba100000625a3754423978a60c9317c58a424e3d&marketName=proto_mainnet
This looks like borrowing is enabled although it isn't.

There should be some info/warning/color highlighting whatsoever

**To Reproduce**
visit https://app.aave.com/reserve-overview/?underlyingAsset=0xba100000625a3754423978a60c9317c58a424e3d&marketName=proto_mainnet

**Expected behavior**
it should be clear to the user that borrowing is disabled

**Additional context**
Initially the ui didn't show borrowing section for assets that have borrowing disabled.
This was very problematic, as borrowing might be disabled at some point but users have still open borrow positions (like e.g. in this example) so the ui was changed to show the borrowing when there's is non-zero open borrow positions.
This is is a lot better but still misleading/confusing as now it looks exactly the same as borrowing enabled assets.

Therefore it would be really good to have some sort of info/warning indicating no new borrows are allowed.

**Comment by defispartan** [comment]
Discussed on Friday to show warning in borrow section of reserve page, I'll get a PR up for it

**Comment by iamanastasia** [comment]
Additionally I'm preparing some designs for different reserve page states. So that everything looks consistent. 
Warning message is a quick fix.
