### ISSUE TITLE
Add 'Available on Ethereum mainnet' label for Governance and Staking

### ISSUE THREAD

**Issue by iamanastasia** [aave/interface#1304]
**Problem**
New members of the community are sometimes confused about using their l2 AAVE (e.g., Polygon network) to vote in Governance, or when staking. Current message (in the description) is hard to notice or find. 

**Possible solution**
If we put a more obvious label (NOT WARNING) it becomes more noticeable and will help users to avoid mistakes. 
<img width="1036" alt="Screenshot 2022-11-04 at 13 22 32" src="https://user-images.githubusercontent.com/92739089/199938168-2ecefc79-02d3-4e91-b820-d67380e216e9.png">
<img width="1032" alt="Screenshot 2022-11-04 at 13 22 25" src="https://user-images.githubusercontent.com/92739089/199938208-95117c0b-212f-43e8-a5dc-5076000e2a59.png">

**Alternative solutions**
—

**Comment by 0x4Graham** [comment]
Shipped.
