### ISSUE TITLE
Refactor: Tooltip Component

### ISSUE THREAD

**Issue by foodaka** [aave/interface#1333]
**Is your feature request related to a problem? Please describe.**
Everytime we add a new warning or message many times we are creating a new component. This is nor following DRY principles and can likely be reproduced into a few <GenericTooltip /> <WarningTooltip> <ErrorTooltip /> etc.

**Describe the solution you'd like**
A robust tooltip to handle most dummy messages passed to it across the system

**Comment by foodaka** [comment]
Makes sense we should encourage the use of this component

**Comment by kaushikriya** [comment]
I will take this up
