### ISSUE TITLE
Refactor MarketWarning component

### ISSUE THREAD

**Issue by drewcook** [aave/interface#1344]
## Tech Debt

Refactor the `<MarketWarning />` component to return an empty JSX tag when the network being passed in is not in a maintained 'frozen markets' list.  Currently, in all theimplementations across the UI, there are additional checks against the market name on if it should be rendered or not.  This logic should be, instead, moved and contained within the `MarketWarning` component itself.

Furthermore, consider renaming the component to `FrozenMarketWarning`, since that is what it is primarily doing.  If there is ever a need to expand to other "global market-based warnings", then this component can be renamed back to `MarketWarning` and expanded upon.

**Comment by Jdecristi** [comment]
@defispartan did you fix this in pr #1141?
