### ISSUE TITLE
fix: display and warnings for isolated assets

### ISSUE THREAD

**Issue by defispartan** [aave/interface#1347]
**Describe the bug**

If an asset has a maxed-out debt ceiling, it currently blocks the asset from displaying in the supply and borrow sections. The asset should always be available to supply or borrow with one exception: if a user is supplying the asset *in* isolation mode, they cannot supply additional collateral with a different asset.

Also remove debt ceiling warning from borrow modal. Not relevant since debt ceiling only affects usage of asset as collateral.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by grothem** [comment]
Link T-2897
