### ISSUE TITLE
borrow fail 

### ISSUE THREAD

**Issue by alexmass101** [aave/interface#1368]
**Describe the bug**
[Internal JSON-RPC error.](https://polygonscan.com/tx/0x8e7aacddc084c4fd0de3ef60865060756491226caf960f66edff5163239fd75c)

**Expected behavior**
borrow 0.005 dai 

**Screenshots**
no 

**Desktop (please complete the following information):**

- OS: win 10
- Browser chrome
- Version [107.0.5304.107]

**Smartphone (please complete the following information):**

-

(https://polygonscan.com/tx/0x8e7aacddc084c4fd0de3ef60865060756491226caf960f66edff5163239fd75c)

**Comment by foodaka** [comment]
@alexmass101 you ran out of gas, can you bump the gas limit on your wallet provider and try again
