### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by iamanastasia** [aave/interface#1382]
**Is your feature request related to a problem? Please describe.**
Need some space for useful links and legal docs that would be easy to find. 

**Describe the solution you'd like**
Add a footer where we can place such links as Terms of Use, Privacy Policy, links to social, etc. Here is how it might look like

![footer desktop](https://user-images.githubusercontent.com/92739089/209127999-a68c31ad-8e19-4ed0-aaa5-cc7ed75f306e.png)

![Footer mobile](https://user-images.githubusercontent.com/92739089/209128008-51c9fcf7-573d-4c8e-99af-90b922b9b18f.png)

The exact list of links is coming soon.

**Comment by foodaka** [comment]
@iamanastasia is there animations? for example i think on the nav we hide on scroll

**Comment by iamanastasia** [comment]
@foodaka Nope, no animations. Always on the bottom of the page.

**Comment by Jdecristi** [comment]
Hey, @iamanastasia I would like to take this on. Do you have some some links so I can get started?
