### ISSUE TITLE
[Bug] Bug when supplying USDC on Polygon

### ISSUE THREAD

**Issue by doanhat** [aave/interface#1394]
**Describe the bug**
Bug when supplying USDC on Polygon

**To Reproduce**

1. Go to Polygon market on AAVE
2. Click on Supply USDC
3. Confirm in Metamask 
4. See error [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal error"}}}'

**Expected behavior**
Transaction confirmed and USDC supplied in AAVE Polygon

- OS: MACOS Monterey 12.6.1
- Browser EDGE 108.0.1462.54

**Comment by 0x4Graham** [comment]
Tried and not an issue.
