### ISSUE TITLE
OP Token Shown in 'Assets to supply' List When Balance is 0

### ISSUE THREAD

**Issue by grothem** [aave/interface#1424]
**Describe the bug**
My balance for OP is zero, and when I switched to the Optimism market, I was seeing this:
![image](https://user-images.githubusercontent.com/23554636/213310360-4a4785cc-b6ad-46d2-a94f-d05d5cd9ce23.png)

**To Reproduce**

1. Go to Optimism V3 market

**Additional context**
The issue seems to be just on the initial fetch of the pool data, because the issue seems to resolve on the next fetch of pool data

**Comment by defispartan** [comment]
Unable to reproduce
