### ISSUE TITLE
Create warning(s) for stETH migration

### ISSUE THREAD

**Issue by defispartan** [aave/interface#1449]
**Describe the bug**

During mainnet v2 -> v3 migration, stETH is wrapped to wstETH for use in the V3 market. stETH and wstETH have different rebasing mechanisms and 1 stETH does not equal 1 wstETH so there should be a notice that the USD value is not changing, only the token balance.

Additionaly, due to a bug in the underlying stETH token, balanceOf can have an imprecision of 1-2 gwei which means migrating stETH will always leave a small amount of dust in V2. This may also warrant a warning.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by foodaka** [comment]
Link T-4954

**Comment by foodaka** [comment]
@JoaquinBattilana did we finish this one? can you close it out if we did

**Comment by defispartan** [comment]
Closed by #1213
