### ISSUE TITLE
Swap Torus connection modal with Rabby

### ISSUE THREAD

**Issue by marczeller** [aave/interface#1471]
**Is your feature request related to a problem? Please describe.**
Nobody use Torus and Rabby is a high quality wallet with a growing userbase

**Describe the solution you'd like**
[clear out the Torus integration and replace it with Rabby integration
](https://github.com/RabbyHub/Rabby)

**Additional context**

![image](https://user-images.githubusercontent.com/21088542/217828434-1596f3eb-c6cc-479a-a564-9081689fb731.png)

**Comment by lyzergic** [comment]
I can take this on if the team wants it. Also Rabby can be connected without removing Torus
