### ISSUE TITLE
in taking the faucet failure or error often occurs

### ISSUE THREAD

**Issue by suhermanid** [aave/interface#1472]
![Screenshot_20230210_074938](https://user-images.githubusercontent.com/68448349/218100351-1bd4391c-ddf3-4e04-a987-2354d003db64.png)
**Describe the bug**
A clear and concise description of what the bug is, including the exact market(e.g. polygon v3) on which it was observed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by defispartan** [comment]
Hi, there have been several changes rolled out to the faucet to address stabiity, there have been several outages due to high volume and/or network gas price
