### ISSUE TITLE
Disappeared stkAAVE during Cooldown for unstaking!

### ISSUE THREAD

**Issue by Webosfritos** [aave/interface#1488]
**stkAAVE during cooldown not shown**

Hi, I have activated the cooldown period to unstake and the balance disappeared from the interface.

This is the transaction hash:
0x40cfc7d1ddd1e85821308840ec209f643dabcd340b2681113092982547a9306e

I can't find a way to make sense of this, even if the wallet had been compromised, the stkAAVE during cooldown period shouldn't move. 

I've been doing this through a Firefox browser in a Mac with OS Ventura 2.2.1 version and a Metamask wallet.

Does any one know if this is an interface problem or can help me finding out what's going on here? This is a pressing matter for me.

Thx!

**Comment by grothem** [comment]
Staked tokens can always be transferred, regardless of cooldown period. The cooldown period just prevents you from redeeming stkAave for Aave. 

It looks like there was an approval transaction here from your account to spend stkAave: https://etherscan.io/tx/0x85f6b7ae90c52613bdb531d54c997bb559cd4cd902d8c3e2e45a8bf8887c5374

And then the tokens were transferred in this tx: https://etherscan.io/tx/0xa8aa3bcd6e9481089d5a2ea8c894f2daaea59843a7526fb888ba93fa77c1cb49

**Comment by 0x4Graham** [comment]
Issue looks dead. Closing.
