### ISSUE TITLE
Error processing the transaction

### ISSUE THREAD

**Issue by BinoyB007** [aave/interface#1507]
**Describe the bug**
Error while supply DAI

**To Reproduce**

1. Go to 'dashboard
2. Click on 'supply DAI
3. Allow transaction 

**Expected behavior**

Transaction not done 

**Screenshots**

![Screenshot_2023-02-27-11-50-43-566_com brave browser](https://user-images.githubusercontent.com/126445481/221490807-140f78d2-dc3d-429c-b334-c504e8049f80.jpg)

**Smartphone (please complete the following information):**

- Device: Android 
- OS: 10
- Browser brave browser
- Version latest

**Additional context**

**Comment by 0x4Graham** [comment]
Closing as covers GHO, which is a separate repo. Issue was to do with the Goerli network.
