### ISSUE TITLE
Failed transaction 

### ISSUE THREAD

**Issue by slappy890** [aave/interface#1511]
**Describe the bug**
I was on aave and transfered and supplied USDC using the polygon network v3. I then tried to swap it for miMatic on Aave and an error came up stating the transaction failed and to contact github. The USDC funds are no longer on Aave or my web3 coinbase wallet they are gone. 

**To Reproduce**

Clicked swap on Aave USDC 
Put USDC funds in to swap to miMatic 
Approved funds 
SIGNED 
confirmed transaction
Attempted to send and received an error 

**Expected behavior**
SWAP USDC FOR MImatic on Aave 

**Smartphone (please complete the following information):**

- Device: Galaxy A32 5G
- OS: ui 5 0
- Browser Coin base web3 Browser App.aave 

**Additional context**

**Comment by defispartan** [comment]
Are you using a Ledger wallet? If so there was an update which may require you to re-enable "Allow blind signing" in Ledger settings

**Comment by 0x4Graham** [comment]
If not already, please raise this on https://discord.com/channels/602826299974877205/1020255268489138216

Closing this here.
