### ISSUE TITLE
URGENT agEUR health factor not updated yet

### ISSUE THREAD

**Issue by chriscrutt** [aave/interface#1533]
USDT needs to be isolated and when it's not it cannot be used as collateral. Thus, the health factor looks correct:
<img width="406" alt="Screen Shot 2023-03-22 at 3 26 59 PM" src="https://user-images.githubusercontent.com/6835463/227052525-71d8ee19-7dd6-42db-8a88-6b7f29ce74f7.png">
That being said, I'd do a check to see if USDT would be isolated on the swap or not and change
`can be collateral        yes -> yes` to `can be collateral        yes -> no` accordingly.
Inversely, agEUR cannot be used as collateral right now because of obvious reasons- which it shows on the UI. However, the health factor is still what it would be if it ***was*** being used as collateral
<img width="413" alt="Screen Shot 2023-03-22 at 3 25 22 PM" src="https://user-images.githubusercontent.com/6835463/227053122-32070a13-b002-4605-a800-32969cf6e801.png">
so `health factor       1.03 -> 1.04` should be `health factor       1.03 -> 0.97`.

unless I am totally wrong and there's something I'm not seeing- fix!

**Comment by grothem** [comment]
Thanks @chriscrutt , good catch.
