### ISSUE TITLE
Staked AAVE missing from platform I staked 8.403442406097 AAVE on 10/31/22 but now its is not showing on my dashboard. Hash is as follows: 

### ISSUE THREAD

**Issue by BJK62051** [aave/interface#1543]
**I staked 8.403442406097 AAVE on 10/31/22 but now its is not showing on my dashboard. Hash is as follows: 0xcf4e2ccb9f709fef89b2c6db5b5efa605ed280bab70de5def5df960baae8b59e. Please restore my AAVE and rewards

Benjamin Kupka

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 0x4Graham** [comment]
Hello, 

Looks like you sold your stkAAVE for ETH in the following tx: https://etherscan.io/tx/0x88625e1f33e957a77c638d3564ebd8e621d592389e2611bb7759f65f20069cd5

Closing issue.
