### ISSUE TITLE
Approval amount warning

### ISSUE THREAD

**Issue by defispartan** [aave/interface#1567]
**Describe the bug**

MetaMask has a feature which works like a bug for certain Aave interface actions. If you peerform an approval of aTokens with a transaction (withdrawing base tokens (goes through WETHGateway all other withdrawals don't need an approval), repay with collateral, collateral swap, or migration) when you go to submit the tx MetaMask will prompt you to update the amount. 

If you select max (current balance) the next transaction trying to spend the full balance will fail because aToken balance is constantly increasing. 

Need to decide if this warrants a message in these modals to prompt that the approved amount must be > current balance to spend all aTokens in a transaction.

**To Reproduce**

Perform an approval of aTokens with a transaction (repay with colalteral, collateral swap, or migration) when you go to submit the tx MetaMask will prompt you to update the amount. 

If you select max (current balance) the next transaction trying to spend the full balance will fail because aToken balance is constantly increasing.

**Expected behavior**

User approves an amount > current balance and tx suceeds.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jdecristi** [comment]
@defispartan can we close this because its been fixed?

**Comment by sbarbarino22** [comment]
ug im getting withdrawal issue for no reason with metamask, spending the whole day trying to figure this out

**Comment by Moderator0xa** [comment]
@sbarbarino22 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
