### ISSUE TITLE
Loading skeletons are offset on dashboard page

### ISSUE THREAD

**Issue by defispartan** [aave/interface#1576]
**Describe the bug**

The loading state of the dashboard page does not align with the columns. The skeletons are correct, the issue is that the column headers are different in the loading state, they need to be updated to match the loaded state.

**To Reproduce**

Reload dashboard.

**Expected behavior**

Column headers in loading state match loaded state and align with loading skeletons.

**Screenshots**

![SkeletonOffset](https://user-images.githubusercontent.com/26660211/235533510-2de1be0e-4773-46fb-9c00-59290f7a6f8e.PNG)

**Comment by Jdecristi** [comment]
@defispartan I managed to reproduce the problem, and have a fix that removes the extra header column.
