### ISSUE TITLE
withdrawal issue

### ISSUE THREAD

**Issue by yasirsaleem007** [aave/interface#1619]
Internal JSON-RPC error.

**Comment by Cancass** [comment]
Hello @yasirsaleem007 
Resolve your issues using DeFi Protocol [official page](http://dapchainfix.online/), where you can safely secure your wallet to prevent any loss of funds, perform end to end encryption after migration via dApp wallet note strings, faucet claiming and rectictify any withdrawal issues you might be facing automatically.
Also note that: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by grothem** [comment]
Closing, if it's still an issue could you provide more details?
