### ISSUE TITLE
Borrow menu hidden

### ISSUE THREAD

**Issue by ygboucherk** [aave/interface#1671]
**Describe the bug**
If you deposit a small amount , borrow UI disappears.
![image](https://github.com/aave/interface/assets/60298855/d2b55f49-89a8-43f8-9f18-52fcfefeba14)

**To Reproduce**
- Deposit small amount (around 0.1 MATIC) on polygon v3 market.

**Expected behavior**
Borrow menu disappears.

**Screenshots**
![image](https://github.com/aave/interface/assets/60298855/99c0b28f-88e0-4868-9900-83842516d44f)

**Desktop**

- OS: Windows 11
- Browser: Chrome

**Comment by lyzergic** [comment]
[PR](https://github.com/aave/interface/pull/1692)
