### ISSUE TITLE
WalletConnect connection disappeared when page is refreshed

### ISSUE THREAD

**Issue by yulafezmesi** [aave/interface#1742]
**Describe the bug**
Wallet connect connection was lost when the Aave browser page refreshed after connection.

**To Reproduce**

1. Open [aave dashboard](https://app.aave.com/) and connect any wallet with WalletConnect. in my case would be TrustWallet
2. Make sure the wallet has been connected.
3. Refresh the Aave Browser page
4. You'll see the connection has been lost TrustWallet, but still able to see aave app.
5. Refresh Aave app again, then you'll notice the connection is gone for both sides.

**Expected behavior**
- Connection shouldn't be lost even though the page is refreshed.

**Desktop (please complete the following information):**

- OS: Mac m1
- Browser Google Chrome
- Version [e.g. 22] 112.0.5615.49

**Comment by grothem** [comment]
@yulafezmesi I'm having trouble reproducing. I tried wallet connect with Trust and one other wallet. Every time I refreshed my connection was re-established.

Are you still seeing this issue?

**Comment by agentmic487** [comment]
@yulafezmesi Are you still getting this issue? If yes i can put you through on what to do.
