### ISSUE TITLE
Add APR moving average line to chart

### ISSUE THREAD

**Issue by tab00** [aave/interface#1751]
**Is your feature request related to a problem? Please describe.**
APR's can change a lot day-to-day, making it difficult to compare and decide which assets on which blockchains would be good to supply.

**Describe the solution you'd like**
Show an additional moving average line (e.g. 20-period) to smoothen out the bumps.

Consider also adding longer-term moving average lines e.g. 50-, 100-, 200-period.

Consider also using *exponential* moving average to give more weight to more recent data.

**Comment by joshuanazareth97** [comment]
Is this being worked on? Can I pick it?
