### ISSUE TITLE
Insufficient funds error in Faucet modal

### ISSUE THREAD

**Issue by defispartan** [aave/interface#1754]
**Describe the bug**

The V3 testnet redeployment #1709 uses permisionless faucet with per-tx limit instead of permissioned faucet executed via backend, so all faucet txns will need the base token of the network.

Currently the faucet modal doesn't handle `INSUFFICIENT_FUNDS` RPC error and display generic tx error.

**To Reproduce**

Try to faucet a reserve on a permisionless faucet market (V3 Scroll Alpha or any V3 testnet post #1709) with an empty wallet

**Expected behavior**

Error message specifying that wallet needs funds to pay for transaction gas.

**Comment by vishesh0123** [comment]
Hi , can you please assign this task to me ..
