### ISSUE TITLE
Aave alarm integration

### ISSUE THREAD

**Issue by nebolax** [aave/interface#1767]
Currently on the aave interface there is a button to set up notifications with Hal project.

<img width="315" alt="image" src="https://github.com/aave/interface/assets/63492346/9c72d6f6-4c11-4996-999e-2611394f4f81">

That's obviously great! But I've also made an aave-specific mobile app where you can track your addresses and receive notifications in case your health factor gets too low or you get liquidated and I think it will make sense to mention this mobile app on the website too. App repo: https://github.com/nebolax/aavealarm (it was developed thanks to a grant from aave grants dao!).

So, I am proposing an addition of some sort of a link to google play & app store on the website.

**Comment by NandyBa** [comment]
Assuming [HAL temperature check](https://snapshot.org/#/aave.eth/proposal/0xa730caeec3c28e014ff456b454186ef41c6c1f382cf0a7caa3d99c4ae16c8318) for integration on the Aave UI good practice can be to do a similar vote.

**Comment by NandyBa** [comment]
@nebolax to you have Aave Alarm grey logo and hover logo as svg as [public/icons/healthFactor/HAL.svg](https://github.com/aave/interface/blob/main/public/icons/healthFactor/HAL.svg) [public/icons/healthFactor/HALHover.svg](https://github.com/aave/interface/blob/main/public/icons/healthFactor/HALHover.svg) ?

**Comment by nebolax** [comment]
> @nebolax to you have Aave Alarm grey logo and hover logo as svg as [public/icons/healthFactor/HAL.svg](https://github.com/aave/interface/blob/main/public/icons/healthFactor/HAL.svg) [public/icons/healthFactor/HALHover.svg](https://github.com/aave/interface/blob/main/public/icons/healthFactor/HALHover.svg) ?

Probably not. I need to create one for the proposal, right?

**Comment by NandyBa** [comment]
> > @nebolax to you have Aave Alarm grey logo and hover logo as svg as [public/icons/healthFactor/HAL.svg](https://github.com/aave/interface/blob/main/public/icons/healthFactor/HAL.svg) [public/icons/healthFactor/HALHover.svg](https://github.com/aave/interface/blob/main/public/icons/healthFactor/HALHover.svg) ?
> 
> Probably not. I need to create one for the proposal, right?

No it's just for integration :) to prepare UI component as curent HAL one.

https://github.com/aave/interface/assets/11545946/d8a66fa4-e8d9-4647-9699-b1435a74f5f4

**Comment by NandyBa** [comment]
I let you submit the proposal you are more legit to do it.

**Comment by NandyBa** [comment]
Feel free to give me your feedback. If you want to test the composant you can do it by checking this branch [feat/1767-add-aave-alarm-app-links](https://github.com/NandyBa/Aave-interface/tree/feat/1767-add-aave-alarm-app-links)

https://github.com/aave/interface/assets/11545946/b54872fe-f0b9-48d4-ac4e-ced39e450adc


Note: icon will be change to your's.

**Comment by nebolax** [comment]
Sure!! Will definitely check it out.

(but looks already great!!)
