### ISSUE TITLE
Standardize Pool approval amounts

### ISSUE THREAD

**Issue by defispartan** [aave/interface#1800]
`supply`, `repay`, `repayWithPermit`, and `supplyWithPermit` are all approving underlying tokens to the Pool contract. Some approvals use a max approval while others use per-tx allowance. This should be standardized or give the option to select max approval vs per-tx.

**Comment by vishesh0123** [comment]
The way we can standardize approval amounts is we should by default use per-tx approval . In case of supplyWithPermit and repayWithPermit we should use per-tx approval  only . And in case of supply and repay we should give user choice if they wanna use max approval

**Comment by vishesh0123** [comment]
<img width="375" alt="Screenshot 2023-10-16 at 11 49 56 PM" src="https://github.com/aave/interface/assets/92142792/c5774d68-51b1-4910-88af-7a76c03286bc">
<img width="379" alt="Screenshot 2023-10-16 at 11 51 19 PM" src="https://github.com/aave/interface/assets/92142792/fc1d5e2a-1a42-4a25-891d-3e4c883a3761">

**Comment by vishesh0123** [comment]
#1812

**Comment by vishesh0123** [comment]
This Closes #1812

**Comment by JoaquinBattilana** [comment]
Hey just to add some context to this, there are some cases that we absolutely need max approval, for example for `repayWithPermit` if you want to do a max repay you need to pass a signature with max approval because it validates it in the contracts

**Comment by vishesh0123** [comment]
> Hey just to add some context to this, there are some cases that we absolutely need max approval, for example for `repayWithPermit` if you want to do a max repay you need to pass a signature with max approval because it validates it in the contracts

Yes , Thanks for correcting . I have updated the code . As you can see in screenshots , I have created the switch for let user select if they wanna use max approval or per-tx approval . But there are the cases where only per-tx approval is possible . (one such case is `supplyWithPermit`) . Thats why , I identified 6 cases where we need to identify if we need to display switch there or not and some other things.

1.`Supply` - In this case we are displaying switch and user has choice to use per-tx approval or max approval 

2.`SupplyWithPermit` - In this case we are not displaying switch as max-approval is not possible here

3.`Repay` (Without Max Repayment) - Here also switch is implemented and user can select per-tx or max approval

4.`Repay` (Max Repayment uint(-1) case) - Switch is getting displayed with Max Approval - Yes but user can not toggle switch here (can not use per-tx approval)

5.`RepayWithPermit` (Without Max Repayment) - Not  Displaying Switch as max -approval is not possible here 

6.`RepayWithPermit` (Max Repayment uint(-1) case) - Switch is getting displayed with Max Approval - Yes but user can not toggle switch here (can not use per-tx approval)

I am open to feedback and further discussion on this . Let's discuss if there are other cases  . You can checkout PR #1812  Just commited updated code . Test it if you can and then we can discuss further
