### ISSUE TITLE
running the interface fails on some dependencies

### ISSUE THREAD

**Issue by fyookball** [aave/interface#1841]
I am just doing the basic commands in the readme with cp .env.example .env.local, then yarn and yarn dev.

 running yarn gave error @coinbase/wallet-sdk#.1.0: The engine "node" is incompatible with this module. Expected version >=10.0.0" Got 8.10.8.  Tried removing that from package.json and then got a similar issue with babel-plugin-macros.
 
 Which "engine node" is it talking about?

**Comment by defispartan** [comment]
This error means you need to update your local NodeJS version

https://www.freecodecamp.org/news/how-to-update-node-and-npm-to-the-latest-version/

**Comment by fyookball** [comment]
Ok thanks.  I had issues on my OS but on a different machine, after I reinstalled nodejs, npm, and yarn, now it works!  

FYI with installing yarn you have to avoid the cmdtest version.
