### ISSUE TITLE
Recent APR data missing?

### ISSUE THREAD

**Issue by tab00** [aave/interface#1872]
**Describe the bug**
The latest chart data point was 3d ago.

**To Reproduce**
See the chart of any supported asset on any blockchain. e.g.:
https://app.aave.com/reserve-overview/?underlyingAsset=0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0&marketName=proto_mainnet_v3

**Expected behavior**
Charts should show all data points of past APR.

**Comment by grothem** [comment]
Closing this, all chart data is coming through ok now. Let me know if you still see issues
