### ISSUE TITLE
Switch features do not factor flashloanable flag in V3

### ISSUE THREAD

**Issue by defispartan** [aave/interface#1880]
**Describe the bug**

Reserves in Aave V3 have a parameter isFlashloanable which is separate from borrowing enabled. 

Collateral switch (and potentially other featuresl) do not have a warning if a flashloan is attempted and the reserve does not support. The max amount should account for whether flashloan can be used.

**To Reproduce**

Supply reserve with flashloanEnabled = false ($AAVE on V3 Ethereum market) -> Open borrow position with low health factor -> attempt to collateral switch full balance

A flashloan will be attempted and txn will fail gas estimation

**Comment by kaegandini** [comment]
There's a serious issue when trying to do anything using the Asset AAVE on ETH network. You can't switch assets, repay debt or do anything. This is something serious that needs to addressed URGENTLY!
