### ISSUE TITLE
APY type change buttons on the migration page need dark text in dark mode.

### ISSUE THREAD

**Issue by helpfulBro** [aave/interface#1897]
**Describe the bug**
When visiting the migration page in dark mode the APY type change buttons cannot be read clearly
![image](https://github.com/aave/interface/assets/25915621/cfaad78d-c94e-4d36-9397-c2a785ac6e6d)

**To Reproduce**

1. Connect wallet with v2 assets (e.g. 0x52dad5f67f8b2f474abf3d49c5d7c25842b7725c)
2. Go to https://app.aave.com/v3-migration
4. See issue

**Expected behavior**
APY type change buttons should be readable similar to below
![image](https://github.com/aave/interface/assets/25915621/db86f944-bf12-42c8-b2e2-21fc85c2f8bc)

**Comment by boombb12138** [comment]
I can fix this. I have reproduce this issue :)
![image](https://github.com/aave/interface/assets/95857565/9362ee5c-0ab3-4a49-a585-f31399c5e543)

**Comment by boombb12138** [comment]
![image](https://github.com/aave/interface/assets/95857565/855e7aa3-c14a-4194-96a9-0cbec8c1d5fb)
![image](https://github.com/aave/interface/assets/95857565/564cd639-608c-4a62-a9fa-7faee061fafc)
Fixed, now it is normal in both light mode and dark mode~~
