### ISSUE TITLE
Inability to withdraw funds

### ISSUE THREAD

**Issue by kmarklor** [aave/interface#1955]
After putting WETH in supply on BASE v3, I can't retrieve them.

1. Go to 'https://app.aave.com/?marketName=proto_base_v3'
2. Click on 'WETH supply'
3. Try to withdraw
4. See error: "while converting number to string, invalid number value '5e-7', should be a number matching (^-?[0-9.]+)."

I'm just waiting to get my money back.

![Capture d'écran 2024-02-09 085332](https://github.com/aave/interface/assets/133235269/76938dc8-21b6-4fa1-8bb8-662cf1478632)

- Windows 11
- Chrome
-121.0.6167.161

**Comment by iichelhadi** [comment]
Hi. has you issue been resolved?
I have similar issue with staked WETH unable to withdraw to metamask
with "Unknown error"

**Comment by kmarklor** [comment]
Yes, uninstall metamask and import your wallet in rabby or an other wallet,
it's juste a bug don't worry
