### ISSUE TITLE
Fail to withdraw fund

### ISSUE THREAD

**Issue by Junlisaac** [aave/interface#1969]
**Describe the bug**
under the Scroll V3 on the app.aave.com

**To Reproduce**

I have supplied the ETH , then want to withdraw it :
1. Click on Withdraw button
3. Select Max to withdraw all the Deposited ETH

See shots:
![IMG_9372](https://github.com/aave/interface/assets/87890294/a2e24fab-3406-4006-9df7-f00fe2f750e9)
![IMG_9368](https://github.com/aave/interface/assets/87890294/e0135c3c-d826-4d95-9c29-50e847c5dd59)
![IMG_9371](https://github.com/aave/interface/assets/87890294/67722138-21c0-43fa-8069-3b39cb809f7e)

**Comment by iichelhadi** [comment]
Hi. has you issue been resolved?
I have similar issue with staked WETH unable to withdraw to metamask
with "Unknown error"

**Comment by cryptscatter** [comment]
Internal JSON-RPC error.

**Comment by Kassioss** [comment]
Eu também estou com o mesmo problema ,não consigo tomar emprestimos ,fazer o repay e aumentar o meu colateral .

**Comment by grothem** [comment]
Likely the same as #1567 

I you are trying to withdraw ETH, you need to make sure the approval amount is high enough to cover the amount to withdraw plus any interest accrued from when you will submit the withdraw tx.
