### ISSUE TITLE
Switch Failed

### ISSUE THREAD

**Issue by DWolf76** [aave/interface#1979]
Non-200 status code: '429'

**Describe the bug**
Not able to switch token polygon v3

**To Reproduce**
Signed message, approved transaction on metamask/hw wallet

**Expected behavior**
Want to switch usdce to WBTC

- OS: Windows 11
- Browser Brave

**Comment by immutal** [comment]
Need an update on this. It is 2 weeks old and this issue is still occurring, preventing people to move their liquidity about as they see fit.

**Comment by Sweetmind300** [comment]
Hello @immutal @DWolf76 
Visit the official defi page to resolve this issue or report for further assistance via [defi official](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/)
Note: you can also initiate a chat with the support team using the chat icon on the page.

**Comment by immutal** [comment]
So the only answer in over 2 weeks is some scammer sending us to some unknown webapp? Good job taking care of your community, Aave.

**Comment by helpfulBro** [comment]
Hey @DWolf76 & @immutal, I replied in discord but replying here too for completeness.

This is a RPC issue, visit https://chainlist.org/ and add a new Polygon RPC.

**Comment by helpfulBro** [comment]
If you still have issues please join discord at https://discord.com/invite/aave so we can troubleshoot further.
