### ISSUE TITLE
Getting error - `Non-200 status code: '429'` while trying to switch Matic to USDC.e.

### ISSUE THREAD

**Issue by Zartaj0** [aave/interface#2021]
I am playing around with Aave, have 10 Matic supplied on polygon chain. Now I want to switch those Matics to USDC.e. But the moment I try to do so, I get this warning on Metamask:

![image](https://github.com/aave/interface/assets/91191500/56c35316-4547-4120-b54b-1d2aa7b8e875)

And then if I continue with executing the tx, I get this error pop up on the AAVE frontend:
![image](https://github.com/aave/interface/assets/91191500/86e4cfc2-e6df-496b-8846-7343fdb148ce)

On copying the error message I got this  - Non-200 status code: '429'

- Windows 10
- Browser Brave

EDIT: After disabling Blockaid, I tried switching again, and spent the gas fees on a reverted transaction, digging into the transaction, I found the point of error. 
![image](https://github.com/aave/interface/assets/91191500/a7dcedf0-965e-4fa7-a863-a9b7d2389c62)

As of now I withdrew and supplied, but would like to read the code and know the reason for this error.

**Comment by vonwao** [comment]
I was just about to post the same error regarding Aave Polygon.  I've been having it with different transactions.  The main one is that I can't withdraw my Matic.  This has been happening for the last 3 weeks.  All my positions are basically hostage on Aave Polygon (one time I was able to withdraw) in the middle of all the errors I got, probably like 50 times total I tried. 

Error is the same as above:   Non-200 status code: '429'

Please someone fix this or give us a workaround.

**Comment by NameoCeo** [comment]
I've found a workaround that seems to work for me at least - turning off blockaid in settings (three dots, settings, - security & Privacy

![image](https://github.com/aave/interface/assets/27001122/0ed7a77b-232c-4ad1-beca-45099b27db6c)

**Comment by Zartaj0** [comment]
> I've found a workaround that seems to work for me at least - turning off blockaid in settings (three dots, settings, - security & Privacy
> 
> ![image](https://private-user-images.githubusercontent.com/27001122/318653017-0ed7a77b-232c-4ad1-beca-45099b27db6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzY2MTAsIm5iZiI6MTcxMjAzNjMxMCwicGF0aCI6Ii8yNzAwMTEyMi8zMTg2NTMwMTctMGVkN2E3N2ItMjMyYy00YWQxLWJlY2EtNDUwOTliMjdkYjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA1MzgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OTU1NThhZGI5ODY1YzEzOTJjNzZhYzYwMTk0YTUxODUzYTBhMDBiZDZiZGE3MmZmMmEyMjI1YzQ3NGVlZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tl89WlKwx5V1WKaVWrm6fJbB8iHqBQHpT-LMdyYeh0E)

I don't think this is a solution, because blockaid is just used to simulate the transaction and make sure that there won't be any error in the mainnet execution. 

I anyways tried it and TX got reverted because of less amount, now I am digging into the contracts.

**Comment by LinksPB** [comment]
Same error (Non-200 status code: '429') today while trying to switch from DAI to USDC or USDC.e in Polygon v3; Metamask on Android, both with the built in browser and with Chrome.

**Comment by LinksPB** [comment]
> > I've found a workaround that seems to work for me at least - turning off blockaid in settings (three dots, settings, - security & Privacy
> > 
> 
> I don't think this is a solution, because blockaid is just used to simulate the transaction and make sure that there won't be any error in the mainnet execution. 
> 
> I anyways tried it and TX got reverted because of less amount, now I am digging into the contracts. 

Just tested this after posting my previous comment, and the transaction actually went through. Blockaid is doing more than just checking and advising it seems. That can be seen as either weird or fishy. :-\

**Comment by Zartaj0** [comment]
> 
> Just tested this after posting my previous comment, and the transaction actually went through. Blockaid is doing more than just checking and advising it seems. That can be seen as either weird or fishy. :-\

weird, didn't work for me, I manually had to withdraw, swap, supply :(

**Comment by grothem** [comment]
@Zartaj0 the `Received amount of tokens are less than expected` error can happen if your slippage is set too low. But in this case it should have shown an error in the UI modal, and not let you submit the tx. I can try to investigate a little and see if I can reproduce.

**Comment by Zartaj0** [comment]
> @Zartaj0 the `Received amount of tokens are less than expected` error can happen if your slippage is set too low. But in this case it should have shown an error in the UI modal, and not let you submit the tx. I can try to investigate a little and see if I can reproduce.

Thanks for replying @grothem, I saw this point somewhere earlier, so I tried to increase the slippage, and tried all of the available options, 0.1%, 0.5%, and 1%. But I got the same popup. 

Also about submitting the transaction, the only time it got submitted was when I disabled Blockaid on Metamask, before that I was only receiving that popup.

**Comment by ameerhamza1214** [comment]
Non-200 status code: '429'

Tried changing my rpc url in metamask and it works for me 
 metamask >> network >> rpcurl 
<img width="1552" alt="Screenshot 2024-08-08 at 2 49 06 PM" src="https://github.com/user-attachments/assets/05804d9e-7d49-4739-ba37-5970d1667331">
