### ISSUE TITLE
Cannot withdraw form scroll market

### ISSUE THREAD

**Issue by Slaweksen** [aave/interface#2030]
I have an issue with withdrawing  funds from Scroll market. I have some ETH there and when trying to withdraw I am getting error:
RotationProvider exceeded max number of retries. Last error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"code\":3,\"message\":\"execution reverted\",\"data\":\"0x4e487b710000000000000000000000000000000000000000000000000000000000000011\"}}","error":{"code":3,"data":"0x4e487b710000000000000000000000000000000000000000000000000000000000000011"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"value\":\"0x0\",\"from\":\"0x5722102fb11e9cba642846933e8f6f89e745b19b\",\"to\":\"0xff75a4b698e3ec95e608ac0f22a03b8368e05f5d\",\"data\":\"0x80500d2000000000000000000000000011fcfe756c05ad438e312a7fd934381537d3cffeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000005722102fb11e9cba642846933e8f6f89e745b19b\"}],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.ankr.com/scroll"}, method="estimateGas", transaction={"from":"0x5722102FB11e9cBa642846933e8F6F89E745B19B","to":"0xFF75A4B698E3Ec95E608ac0f22A03B8368E05F5D","value":{"type":"BigNumber","hex":"0x00"},"data":"0x80500d2000000000000000000000000011fcfe756c05ad438e312a7fd934381537d3cffeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000005722102fb11e9cba642846933e8f6f89e745b19b","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.3)

I was able to pay of my debt withdrawing a portion of my holdings before, but all the rest is stucked on the platform.

- OS: windows 10
- Browser chrome
- Version 123.0.6312.106

Is there any way to get it fixed?

**Comment by foodaka** [comment]
Can you try another RPC or contact support on discord
