### ISSUE TITLE
Impossible to withdraw

### ISSUE THREAD

**Issue by Catamarcus** [aave/interface#2046]
I cannot withdraw even a small amount of wbtc

No matching key. keychain: e6b607f12d10a81a35c4023904fe15b1cf56b7a7431a265603769d6e21e9dd29

**Describe the bug**
A clear and concise description of what the bug is, including the exact market(e.g. polygon v3) on which it was observed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sweetmind300** [comment]
Hello @Catamarcus 
Have you been able to resolve this issue yet?
