### ISSUE TITLE
AAVE Arbitrum V3 Token Approval Bug

### ISSUE THREAD

**Issue by caoyishong** [aave/interface#2081]
**AAVE Arbitrum V3**
Token approval is not revoked although the user deposited and withdrew with specific amount on AAVE Arbitrum V3 market.

**To Reproduce**

1. Go to 'Arbitrum V3 Dashboard'
2. Deposit USDC any amounts
3. Withdrew the deposited USDC all or with specific amount
4. Go to token approval page of Arbitrum Explorer (https://arbiscan.io/tokenapprovalchecker)
5. Error - Token approval will still need to be revoked 

**Expected behavior**
If you have deposited your token with either specific amount or all, the token approval must not have been left or revoked. 

**Desktop (please complete the following information):**
- Windows 11
- All browser
- latest versions

**Additional context**
I have uploaded the video with restricted link.

https://drive.google.com/file/d/1SzChtMpf1FpmvDOQgZ7bhJhj29V8FrBP/view?usp=sharing

**Comment by helpfulBro** [comment]
As per reply in discord, please open a ticket in #help and supply the video there without password so we can diagnose.

**Comment by caoyishong** [comment]
> As per reply in discord, please open a ticket in #help and supply the video there without password so we can diagnose.

uploaded in dc.

**Comment by helpfulBro** [comment]
Replied in discord, the approval only remains active in Arbiscan (and not revoke cash).
This is because Arbiscan caches the lookup as indicated by the date/time stamp on the revoke page.

TL:DR approval is working as expected and correct on the blockchain.

**Comment by helpfulBro** [comment]
Resolved, can close.
