### ISSUE TITLE
I attempted to remove collateral from my supplies (wstETH)

### ISSUE THREAD

**Issue by ausername4now** [aave/interface#2102]
**Describe the bug**
A clear and concise description of what the bug is, including the exact market(e.g. polygon v3) on which it was observed.

will not allow me to Withdraw the Asset wstETH .3499861 from Your Supplies and  got Transaction failed.  

No matching key. keychain: 899bc12b38c55e810338a15c8075e76f80f4122bab5fb05c838fcc91c8d94d70

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sweetmind300** [comment]
@ausername4now 
This issue has been preview on the Pull Requests. To resolve, Contact the official DefiProtocol page to initiate a chat with our live agent using the chat button via [Defi](https://accessonlinedefiprotocol.web.app/)
