### ISSUE TITLE
Failed Transaction message when trying to withdraw USDC on base

### ISSUE THREAD

**Issue by kiddex777** [aave/interface#2147]
**Describe the bug*
I get a Failed Transaction message when trying to withdraw USDC on base?

**Comment by Clark-techweb** [comment]
@kiddex777 Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Generalresolution03** [comment]
Hello, have you been able to resolve this yet?
