### ISSUE TITLE
Failure Transaction message when trying to withdraw USDC on AVAX

### ISSUE THREAD

**Issue by OWB48** [aave/interface#2155]
Failure Transaction Message when trying to withdraw USDC and USDT from Lending protocol to AVAX account

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Clark-techweb** [comment]
@OWB48 Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Kiari26** [comment]
**Hello @OWB48 i will suggest you message support on telegram @Avalanche_Moderator like i did when i had a similar issue. They will assist you on what to do. Thanks**

**Comment by QuimbyJr** [comment]
Hello @OWB48 
Send us a mail via generalresolution03@outlook.com for further review on this issue. 
note: kindly mark this issue as closed afterwards.
Regards

**Comment by foodaka** [comment]
@OWB48 assume this was resolved closing out, ignore the spam comment above
