### ISSUE TITLE
Can't Supply Collateral or Borrow

### ISSUE THREAD

**Issue by senjugit** [aave/interface#2163]
**Describe the bug**
Can't supply collateral for wbtc and borrow usdt on polygon v3 market

**To Reproduce**
This is the error: No matching key. keychain: df116c48e7ab3362740cde1231c72f379c30a5f95ba79cbd42339a65a26a5db9

**Expected behavior**
Should be able to supply or borrow

**Screenshots**

**Desktop (please complete the following information):**

- OS: iOS
- Browser: MetaMask
- Version

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro
- OS: iOS 17.6.1
- Browser: MetaMask
- Version: 7.28.1

**Additional context**

**Comment by baenaAb** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@senjugit

**Comment by QuimbyJr** [comment]
Have you been able to resolve this yet?

**Comment by defispartan** [comment]
This is an intermittent error that can occur when connecting to a cancelled WalletConnect session, it should be resolved by disconnecting and reconnecting the wallet.

If that doesn't work you can also try doing a hard site refresh (ctrl + shift + r) or clearing the browser cache.
