### ISSUE TITLE
unleash

### ISSUE THREAD

**Issue by xadro23** [aave/interface#2178]
**Describe the bug**
A clear and concise description of what the bug is, including the exact market(e.g. polygon v3) on which it was observed.

HTTP request failed.

URL: https://rpc.partner.testnet.storyprotocol.net/
Request body: {"method":"eth_blockNumber","params":[]}

Details: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
Version: viem@2.17.3

**Comment by summerly01** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@xadro23

**Comment by Kiari26** [comment]
This is due to a server-side issue or a misconfiguration.  
Summery01 is a scam. This is a phishing link. Don’t click on the link

**Comment by defispartan** [comment]
@Kiari26 is correct, this should be resolved by doing a hard refresh (ctrl + shift + R) or clearing the browser cache
