### ISSUE TITLE
bug issue regarding faucet claim

### ISSUE THREAD

**Issue by Xboy4real** [aave/interface#2196]
**Describe the bug**
A clear and concise description of what the bug is, including the exact market(e.g. polygon v3) on which it was observed.

**To Reproduce**

4. See error  insufficient funds for intrinsic transaction cost (error={"code":-32603,"message":"insufficient funds for gas * price + value: balance 42359234226108580, queued cost 30865647328977380, tx cost 25581087023904544, overshot 14087500126773344"}, method="sendTransaction", transaction=undefined, code=INSUFFICIENT_FUNDS, version=providers/5.5.3)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Xboy4real** [comment]
![Uploading download (48).png…]()

**Comment by defispartan** [comment]
This error means the wallet submitting the transaction does not have sufficient funds to cover the gas cost of the transaction

For example, if attempting to use the faucet on Sepolia testnet, then the wallet needs a balance of Sepolia testnet ETH
