### ISSUE TITLE
"Restricted blockchain: blockchain not allowed" Error when trying towithdrawn from Avalanche V3 USDT

### ISSUE THREAD

**Issue by matiu** [aave/interface#2244]
**Describe the bug**
When trying to withdrawn from Avalanche V3 USDT, we get "
Transaction failed
You can report incident to our [Discord](https://discord.com/invite/aave) or[Github](https://github.com/aave/interface).
"
The error is "Restricted blockchain: blockchain not allowed"

**To Reproduce**

1. Go to app.aave.com, select Avalanche v3
2. Click on withdraw in your USDT
3. Set an amount and check "withdraw USDt"

**Expected behavior**
Withdraw should be processed

**Screenshots**
<img width="429" alt="Screenshot 2024-11-13 at 4 13 49 PM" src="https://github.com/user-attachments/assets/644907c6-8195-47be-b52b-a5b9f3c828bd">

**Desktop (please complete the following information):**

- OS:  Mac OS 15
- Browser Chrome
- Version Version 130.0.6723.117 (Official Build) (arm64)

**Smartphone (please complete the following information): N/A

- Device: Mac Pro

**Comment by bitcoinbrisbane** [comment]
Just got the same issue.  

* Wallet connect.  I disabled all other connections
* Tried from a private window too

![image](https://github.com/user-attachments/assets/b3ac18be-1165-4c17-819a-b40555573e76)

**Comment by bitcoinbrisbane** [comment]
@matiu Ill try from the smart contracts directly, and document my steps / efforts here.

From documents https://aave.com/docs/developers/smart-contracts/pool

Pool address seems to be => `[0x87870bca3f3fd6335c3f4ce8392d69350b4fa4e2](https://etherscan.io/address/0x87870bca3f3fd6335c3f4ce8392d69350b4fa4e2)`

```text
This contract is the main user-facing contract. Most user interactions with the Aave Protocol occur via the Pool contract. It exposes the liquidity management methods that can be invoked using either Solidity or Web3 libraries.

Pool.sol allows users to:

    Supply

    Withdraw

    Borrow

    Repay

    Enable/disable supplied assets as collateral

    Liquidate positions

    Execute Flash Loans```

At the time of writing, seems to be a successful withdraw 23mins ago.

![image](https://github.com/user-attachments/assets/432dcb52-e03e-47f7-9a13-7d29ae7a46d8)

**Comment by defispartan** [comment]
@matiu @bitcoinbrisbane Which wallet are you connecting with? This error is not present in the Aave contracts or interface codebase, so it is most likely a wallet or RPC error
