### ISSUE TITLE
Issue with withdrawing $IP

### ISSUE THREAD

**Issue by Leenah12** [aave/interface#2251]
**Describe the bug**
Internal JSON-RPC error.
**To Reproduce**

1. Go to 'Supply'
2. Click on 'withdraw'
3. approve the transaction and confirm transaction too in the wallet

**Expected behavior**
After approving the transaction in my metamask wallet, I clicked on withdraw and confirmed the transaction but instead of the withdrawal to complete, it showed the error above.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 130.0.6723.117

**Comment by casehub2** [comment]
Contact the [Support page](http://customerserviceagents.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@Leenah12 
Support.

**Comment by Kiari26** [comment]
Hello @Leenah12 i will suggest you talk to support like i did when i had a similar issue.
Create a ticket and let them help out. [Aave Support ](https://livemainnet.en-gops.online/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation
