### ISSUE TITLE
Updating dashboard data for repay 

### ISSUE THREAD

**Issue by MareskoY** [aave/interface#454]
for all v3 test markets updating data on dashboard take to much time

Steps:
1. borrow any asset
2. repay half 
3. wait till get success confirmation in modal 
4. close modale

Result:
- next 30-60 sec we see old borrow value, updating should be happened at the same time as we get confirmation in modal 

![updating dashboard](https://user-images.githubusercontent.com/18032275/157802300-f7c41dfe-ca3e-44ce-8cc2-af785bb11fba.gif)

**Comment by MareskoZ** [comment]
i think that we could triggering updating of table after get success screen in modal

**Comment by defispartan** [comment]
Pre-release, lots of improvements to reserves fetching schema since this issue was create
