### ISSUE TITLE
add image optimization to build pipeline

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#46]
Could happen on merge to master, same with i18n actually :thinking:

**Comment by defispartan** [comment]
@sakulstra Is this still relevant? 

@drewcook mentioned that we could use https://nextjs.org/docs/api-reference/next/image for simpler image optimisation

**Comment by drewcook** [comment]
Yep, lots of wins using the built in `<Image/>` from `next/image and low hanging fruit.  We're currently using native `<img/>` tags, so this could be an easy lift and bang for the buck.

**Comment by sakulstra** [comment]
You can't use next image on static export as they need a server side. It only really works on vercel, not with ipfs.

Did this in another PR though so lint staged now optimizes svgs on commit.

**Comment by drewcook** [comment]
@sakulstra Okay cool, good to know about the husky hook, so looks like we're using `svgo` for this.  Sounds good!
