### ISSUE TITLE
Add cypress automated tests to ci

### ISSUE THREAD

**Issue by sendra** [aave/interface#487]

**Comment by MareskoZ** [comment]
from my side all is ready 

notions for @RoRu 

base:
- PR https://github.com/aave/interface/tree/cypress-merging

what need to do:
1. setup CI for branch deployment with smoke scopes in parallel, commands:
- `yarn run test:main-v2-smoke`
- `yarn run test:amm-v2-smoke`
- `yarn run test:polygon-v2-smoke`
- `yarn run test:avalacnhe-v2-smoke`
- `yarn run test:arbitrum-v3-smoke`
- `yarn run test:avalacnhe-v3-smoke`
- `yarn run test:fantom-v3-smoke`
- `yarn run test:polygon-v3-smoke`

2. setup CI before live deploying with full scopes  in parallel, commands:
- `yarn run test:main-v2-full`
- `yarn run test:amm-v2-full`
- `yarn run test:polygon-v2-full`
- `yarn run test:avalacnhe-v2-full`
- `yarn run test:arbitrum-v3-full`
- `yarn run test:avalacnhe-v3-full`
- `yarn run test:fantom-v3-full`
- `yarn run test:polygon-v3-full`

a good example of implementation https://github.com/aave/aave-ui/tree/master/.github 

also need to add a secret variables:
- TENDERLY_KEY
- TENDERLY_ACCOUNT
- TENDERLY_PROJECT
