### ISSUE TITLE
Negative net APY

### ISSUE THREAD

**Issue by Essah10** [aave/interface#532]
![image](https://user-images.githubusercontent.com/76067798/158858754-f5941c21-7f98-4205-99c3-346713bf5fc8.png)

This guy borrowed something and have a negative apy

**Comment by foodaka** [comment]
@iamanastasia what are your thoughts on this one

**Comment by sakulstra** [comment]
net apy is a little weird construct to be honest. Didn't do the math, but i assume it's correct but not very intentional.
We define net apy as the apy relative to the net worth.
So in this case it means your losing 3.4% on 150k net worth over a year which seems correct.

**Comment by sendra** [comment]
Maybe we could put and explanation to it so people dont get as confused?
