### ISSUE TITLE
e-mode 'learn more' link does not link to relevant information.

### ISSUE THREAD

**Issue by helpfulBro** [aave/interface#540]
e-mode 'learn more' link location
![image](https://user-images.githubusercontent.com/25915621/158911936-d41a9f5c-03c3-4ace-98a7-50a6fff08157.png)

Takes the user to https://docs.aave.com/faq/

Please update FAQ and connect directly to the e-mode info page.

**Comment by foodaka** [comment]
Currently awaiting update in FAQ
