### ISSUE TITLE
Market icons defaulting to ETH for some users

### ISSUE THREAD

**Issue by helpfulBro** [aave/interface#541]
User 1 : Brave Version 1.36.112 Chromium: 99.0.4844.51 on MacOS

Example
![image](https://user-images.githubusercontent.com/25915621/158913128-a3baf19c-a22b-45ea-95dd-7cf59553320c.png)

**Comment by sakulstra** [comment]
They might need to do a hard refresh as the issue was already solved

**Comment by helpfulBro** [comment]
Thanks, closing.
