### ISSUE TITLE
Cooldown time left is negative in AAVEv3, unclaimable stAAVE

### ISSUE THREAD

**Issue by jblachly** [aave/interface#547]
**Describe the bug**
My stkAAVE claim cooldown period was started under AAVEv2, and ended on 17 March. The interface was transitioned to AAVE v3 around this time.

At this moment, I have approximately 12h left in my cooldown period. AAVEv2 at classic.aave.com shows this and allows me to claim, (albeit with a high gas cost)

AAVEv3 shows a disabled button reading  "Cooling down" (even though the cooldown period passed) and Cooldown time left "-2d-12h-33m" which is ticking progressively more negative.

Ultimately, I was hoping to use v3 to claim in order to spend less gas when unstaking/claiming.

**To Reproduce**

1. Visit "stake" on either app.aave.com or classic.aave.com

**Screenshots**
Attached
![Screen Shot 2022-03-18 at 12 29 54 PM](https://user-images.githubusercontent.com/5987153/159044027-a349a1c6-d878-4922-ab4d-d9feb751ee23.png)

**Desktop (please complete the following information):**
 - MacOS 12
 - Firefox (latest)

**Comment by sakulstra** [comment]
Created a pr in #551 to fix the ui, **but** your hopes on less gas intensive claiming will not be full-filled. Staking on v2 is the same as on v3 right now. THings might improve in case https://governance.aave.com/t/arc-aave-governance-v3/6980#advantages-compared-with-v2-5 moves forward though.
