### ISSUE TITLE
Setting custom gwei in staking model causes client side exception

### ISSUE THREAD

**Issue by foodaka** [aave/interface#565]
**Describe the bug**
Setting custom gwei in staking model causes client side exception

**To Reproduce**
1) go to staking page
2) click stake
3) set custom gwei for tx
4) enter two dots .. OR delete the value
"Application error: a client-side exception has occurred (see the browser console for more information)

![Mar-23-2022 09-12-38](https://user-images.githubusercontent.com/8342048/159664104-47af0dc9-5966-4310-83d2-bf3c32148629.gif)

**Expected behavior**
Should be able to set custom gwei and app not crash

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sendra** [comment]
Should we discuss about removing the gas widget?. I think it was added just to show the user a estimation of what the transaction would cost. but I think that we could still do this but letting users choose the gas might be too confusing, when wallets now a days manage this much better

**Comment by foodaka** [comment]
Will delegate this responsibility to the wallet. We will keep the gas estimation.

**Comment by foodaka** [comment]
Add tooltip indicator to set the gas in the wallet
