### ISSUE TITLE
Repay with collateral

### ISSUE THREAD

**Issue by Essah10** [aave/interface#573]
Hi guys

With the new UI the user cant repay with his collateral in the ethereum v2 market. He said he can only see it with the classic v2 UI![image](https://user-images.githubusercontent.com/76067798/159982937-f7d1fe82-0df1-4940-95e2-44ff930d0a0f.png)

**Comment by sakulstra** [comment]
That's a known issue.

There's a work in progress to port repay with collateral to all markets herehttps://github.com/aave/interface/pull/448 in case someone wants to pick that up.

**Comment by sakulstra** [comment]
duplicate of -#638
