### ISSUE TITLE
Governance page missing remaining time

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#588]
**Is your feature request related to a problem? Please describe.**
On the proposal page in governance it's not clear how much time is remaining:
https://app.aave.com/governance/ <- here it's visible
https://app.aave.com/governance/proposal/68/ <- here it's not

**Describe the solution you'd like**
Show the raiming time, as it's an important information.

**Additional context**
![image](https://user-images.githubusercontent.com/4396533/160400130-9b0fcf8d-4ecf-4536-b12f-c5f8ea599ab1.png)
![image](https://user-images.githubusercontent.com/4396533/160400220-4a248ecc-8678-4954-a56d-f774a8894972.png)

**Comment by foodaka** [comment]
What about the active ends in 7 hours on the top left?

**Comment by sakulstra** [comment]
Yes that's the correct number but it's only visible on the list page, not on the proposal page which is shared on Twitter and so on

**Comment by sakulstra** [comment]
@iamanastasia  Another thing to consider is that we only show if quorum is reached but no details on when this is.

The data we have is:
- Current total votes (yae + nay)
- required total votes (the actual quorum needed)
- votes needed (the diff of the two)

I think the last two should be shown on the details panel on the right.

**Comment by iamanastasia** [comment]
Added to figma: https://www.figma.com/file/Q5GcZP2udHS24pOfLKNTIz/Desktop-views?node-id=2239%3A876861

Overview:
<img width="896" alt="Screenshot 2022-03-29 at 15 26 03" src="https://user-images.githubusercontent.com/92739089/160601226-b36f8d27-387b-43e0-84c4-ef5ac2f7f144.png">


Please, adjust page layout:
- there is a separate card for user info
- separate card for voting info
- separate card for proposal details

**Comment by iamanastasia** [comment]
Sorry, have slightly different suggestion for that:
![Proposal list — mobile](https://user-images.githubusercontent.com/92739089/160830333-df45acf1-9b53-480e-9b41-19ac01d23588.png)
![Proposal details — mobile](https://user-images.githubusercontent.com/92739089/160830345-c2f21451-6a51-4fb0-a184-3c75aec14a6b.png)
![Governance — proposal page](https://user-images.githubusercontent.com/92739089/160830350-ca01e8a8-32b5-42f9-99e5-cb3156b9e0f6.png)
![Governance — proposal list](https://user-images.githubusercontent.com/92739089/160830355-e979d3e6-f3a6-43d5-81ab-5a8e06ddbb41.png)

1. Let's fix Status wording a bit for queued and active. 
2. Show the timer/date both — on the list and on the proposal page.
3. We can group Quorum and Differential values, so it's easier to read them

Added how it might look like in mobile (page switcher helps to access voting info with 1 click)
