### ISSUE TITLE
Market size should have ability to show native token 

### ISSUE THREAD

**Issue by foodaka** [aave/interface#606]
**Is your feature request related to a problem? Please describe.**
Feedback Reported: Previously we had the ability to change from the native currency to USD. 

**Describe the solution you'd like**
We should also show the native currency of the asset, either a way to toggle it or below has the USD value.
![Screen Shot 2022-03-29 at 4 55 58 PM](https://user-images.githubusercontent.com/8342048/160671360-554ff1bf-8c67-4167-a10b-e3210e135fdf.png)

Or
![2022-03-29 18 33 49](https://user-images.githubusercontent.com/8342048/160671419-4a6b8043-89ea-422d-ac05-6b6a0cc2ba15.jpg)

**Comment by sakulstra** [comment]
Do I really want/ need this number here? Is it sth frequently reported? I agree that on details page it should be shown. On markets page it might be to much and does not add to much value.

**Comment by iamanastasia** [comment]
One way we can do that without overloading the page with info is to put numbers together within 1 cell. 

Preview:

![Markets page desktop](https://user-images.githubusercontent.com/92739089/161734738-e4fb74e3-a39f-4854-bdec-85a54febbad6.png)
![Markets page mobile](https://user-images.githubusercontent.com/92739089/161734758-d4916897-ad70-492a-ae74-89bc79ec43ff.png)

**Comment by sakulstra** [comment]
@iamanastasia looks reasonable to me, but would be equally as important or even more important on the [details page](https://app.aave.com/reserve-overview/?underlyingAsset=0x4fabb145d64652a948d72533023f6e7a623c7c53&marketName=proto_mainnet)

**Comment by iamanastasia** [comment]
@sakulstra yeah..We can easily add those to supply/borrow section. Need to think a bit how to design overview number
<img width="527" alt="Screenshot 2022-04-08 at 15 18 41" src="https://user-images.githubusercontent.com/92739089/162425712-4b80bdc5-4bed-48bc-ac54-3e6654eb2cbb.png">
<img width="393" alt="Screenshot 2022-04-08 at 15 18 37" src="https://user-images.githubusercontent.com/92739089/162425719-a296ee3b-b94d-4875-a655-b2896405a6d5.png">
s
