### ISSUE TITLE
Usage of the Max button causes issues for repayments and borrows

### ISSUE THREAD

**Issue by helpfulBro** [aave/interface#609]
## Prerequisites

- [X ] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

1. Sometimes when a user is repaying debt and uses the Max button, the UI never presents the option to submit the transaction as it is constantly updating and calculating as interest accrues.
![image](https://user-images.githubusercontent.com/25915621/160506987-98a338d9-d582-4ca2-833b-5ded3e586bdd.png)

2. Sometimes when a user is borrowing and uses the Max button, the UI shows an error related to aToken
![image](https://user-images.githubusercontent.com/25915621/160506935-a5c00279-3563-423a-8dd2-4d6b3a66d00a.png)

## Expected Behavior 🤔

1. The UI should ask the user to pay slightly more than the total debt, and refund the unused portion in the same TX. Or if this is not possible, the UI should update less frequently to allow time for the user to submit the transaction.

2. The Max button should work as expected and not show an error, perhaps similar to the issue above less frequent updates/calculations will allow the user to submit he transaction.

## Steps to Reproduce 🕹

Steps:
Repay
1. Borrow WETH from Polygon V2 market
2. Repay WETH using v3 interface
3. Tap Max when repaying 

Borrow
1. Borrow USDC from Polygon V2 market using v3 interface
2. Tap Max when prompted for borrow amount

## Your Environment 🌎

<details>
  <summary>info</summary>

```
  browser: chrome
  os: win10
  vpn: yes
```

Console errors:
```
[error]: ...
```

</details>

**Comment by sendra** [comment]
closing as it looks like user is using a copied aToken implementation and pointed it to the pool and because his token is not listed on Aave, it will fail on the finalize transfer and that is why the specific error shows.

Regarding first issue, looks like it an rpc connection problem, and that is why it keeps loading, as it doesnt get any response
