### ISSUE TITLE
Include a secondary token label

### ISSUE THREAD

**Issue by helpfulBro** [aave/interface#647]
**Is your feature request related to a problem? Please describe.**
On some chains multiple versions of the same token exist depending on the bridge used.

Example : Wormhole UST vs Wrapped UST on ETH mainnet.

Depending on which DEX is used the user may end up with the incorrect token to that being used within Aave.

**Describe the solution you'd like**
Include a secondary smaller token label that allows for an additional description, and perhaps a link out to the token contract.

Example: 
UST
(Wormhole) [link to token contract]

UST
(Wrapped) [link to token contract]

**Comment by sakulstra** [comment]
The top `name` is an arbitrary name hardcoded in the ui (if not being set, falling back to symbol).
If there's confusion this should imo be used to specify a more concrete name.

![image](https://user-images.githubusercontent.com/4396533/162418764-36b7d1a7-ce37-41d2-a765-02f7511b3aaf.png)

If the symbol name is unique you can just add a line [here](https://github.com/aave/interface/blob/main/src/ui-config/reservePatches.ts#L20) if it's not unique you can map an address to a name [here](https://github.com/aave/interface/blob/main/src/ui-config/reservePatches.ts#L70)

**Comment by helpfulBro** [comment]
Thanks, I can't edit the code so here is my suggestion

`  if (
    underlyingAsset.toLowerCase() === '0xa693B19d2931d498c5B318dF961919BB4aee87a5'.toLowerCase()
  ) {
    return { iconSymbol: 'UST', name: 'UST (Wormhole)', symbol };
  }`

**Comment by sakulstra** [comment]
> and perhaps a link out to the token contract.

I think this would actually make sense. Currently I copy the address part from the url and paste it to the explorer. Would be nicer if there was a link on the overview page directly @iamanastasia
