### ISSUE TITLE
Navigation is not indicating which page you are currently on

### ISSUE THREAD

**Issue by foodaka** [aave/interface#655]
**Describe the bug**
When the user navigates the app, we should show which page they are currently on. We had it previously but somehow it is not showing which active page the user is one.

**To Reproduce**
1. Go to any page on the aave app
2. See the navigation bar
3. It does not show which page the user is active on

**Expected behavior**
![Screenshot 2022-04-08 at 14 32 57](https://user-images.githubusercontent.com/8342048/162695608-8e4ff611-4739-4f23-a391-7136048ce209.png)

**Screenshots**
<img width="930" alt="Screen Shot 2022-04-11 at 9 23 58 AM" src="https://user-images.githubusercontent.com/8342048/162695559-f34763d5-ac02-4be2-9042-f63af6ce91b2.png">

**Comment by sakulstra** [comment]
I think this might have happened here: https://github.com/aave/interface/pull/555/files#diff-2130ee7ba373c826c5d0ea9e6059b59610879993aaee831343904ffdbd22b892L42 it's a bit weird though that no type error was yielded as it seemed unused. Not sure if that's it though.
