### ISSUE TITLE
Redirect user to markets when wallet is not connected

### ISSUE THREAD

**Issue by foodaka** [aave/interface#660]
**Is your feature request related to a problem? Please describe.**
Currently when a user is not connected to the wallet we take them to the dashboard page. For example from the website we take them directly to the dashboard

**Describe the solution you'd like**
If a user is not connected to the wallet, we should take them to the markets page. From there they can go to the dashboard to connect the wallet.

**Comment by defispartan** [comment]
Superseded by Discussion https://github.com/aave/interface/discussions/696
