### ISSUE TITLE
Incorrect amount for funds in safety module

### ISSUE THREAD

**Issue by defispartan** [aave/interface#662]
On the staking page, the amount listed under "funds in the safety module" is much lower than the actual amount.

As of today, it's listed as $157m but should be $697m. The landing page uses the same contract to calculate the correct amount so it's just a calculation issue.

**Comment by sakulstra** [comment]
For me it is 750M$ on production - do you perhaps have testmode enabled? In test mode this will show kovan market.

Idk. why this decision was taken and i think it's highly confusing tbh. Especially as on governance it's not that way.

**Comment by defispartan** [comment]
Yep, that was the issue

I'll keep this issue open and switch to always show the mainnet data since I can't imagine why someone would want to interact on Kovan, and it can definitely lead to confusion
