### ISSUE TITLE
Swap dialog should be up to the design specifications

### ISSUE THREAD

**Issue by foodaka** [aave/interface#664]
**Is your feature request related to a problem? Please describe.**
The swap dialog works as expected, but is not yet up to the design specifications in figma.

1) We didn't finish input parts. It's not clear if should show some rate details, enable swappable amount input, etc.
2) Previously we decided that price slippage would be a collapsable field, so that new to crypto users will not be confused.
3) Tx overview section can contain details about APY rate, incentives, health factor and collateral usage.

**Describe the solution you'd like**
Update the dialog to the correct design specifications

<img width="279" alt="Screen Shot 2022-04-13 at 9 31 06 AM" src="https://user-images.githubusercontent.com/8342048/163134565-5c88092f-c9b9-4601-83f7-39927699fcf7.png">

**Comment by sakulstra** [comment]
just to give some context on why I didn't add the `custom` initially .

I couldn't figure out if there's some sort of mev protection, so i think there isn't - in turn this means that when the amount is high enough and slippage is high enough so it's worth the gas I'd assume the custom slippage will be maxed out. So to protect users from themselves it seemed like a reasonable tradeoff to me not not allow a `custom` setting. 

---

I'm not :100: sure this concern is valid. Even if true it might make sense to add a custom with max 5% or so, it's just sth one should think about before implementing,

**Comment by iamanastasia** [comment]
Hey! Design suggestion on looks and feels.
<img width="1305" alt="Screenshot 2022-05-18 at 12 54 42" src="https://user-images.githubusercontent.com/92739089/168999899-3cd69c47-2518-4510-a2c6-f21f0376b534.png">
<img width="1252" alt="Screenshot 2022-05-18 at 12 55 02" src="https://user-images.githubusercontent.com/92739089/169000648-9c700dcd-dde1-475b-a1ac-c0610ea4dcc7.png">

General:
1. Price impact and slippage tolerance new UI elements and positions.
2. New tx details
3. Alert icon to highlight changes in the future supply after swap. 

An example with asset swap that can't be collateral:
1. Disable button if user will be liquidated after swap? (e.g., he only has ETH as collateral and tries to swap all of it to BUSD which cannot be collateral). 


Let me know what you think.
My original desire was to enable both inputs, but it seems like we can't do that technically. So there are just more visual changes.

**Comment by foodaka** [comment]
@sakulstra @sendra any feedback on your side ?

**Comment by foodaka** [comment]
Should the price impact and slippage information be together? The rest of it looks great @iamanastasia

**Comment by iamanastasia** [comment]
@foodaka not really. They can be in different places as slippage tolerance is a set up might be hidden in general setting for example, and price impact is just shown there for information.

@sakulstra glad you've asked! Here, we have a prototype for that — just a select-dropdown with options + paraswap reference

https://user-images.githubusercontent.com/92739089/169304932-dd14a3cf-14e3-4d46-ba27-58a3bfa68101.mov
