### ISSUE TITLE
Getting Transaction Failed / Terminated in https://app.aave.com with stETH Withdraw, Borrow & Swap

### ISSUE THREAD

**Issue by Marx-Melencio** [aave/interface#668]
This always happens whenever I try to borrow, withdraw and swap my stETH. Here are more details about my issue:

First, I successfully  connected my KeyRing Pro wallet through Wallet Connect in http://app.aave.com
Second, I then successfully deposited stETH.
But now, I keep on getting transaction failed / terminated.

What could be the problem?
My wallet address is 0x3cdf77b10bf1a5e3e25b9750ea325981256df317.

Please help. Thanks!

**Comment by sakulstra** [comment]
Not familiar with KeyRing Pro, but looking on [etherscan](https://etherscan.io/address/0x3cdf77b10bf1a5e3e25b9750ea325981256df317) it seems like the address has close to 0 eth balance so you might not be able to afford a withdrawal. Eth balance is ~3$ where a withdrawal at current market conditions is around ~25$.

**Comment by Marx-Melencio** [comment]
Thanks a lot, @sakulstra ... Didn't realize transfer fees need to come from my ETH wallet, and not deducted from my AAVE balance when doing withdrawals, swaps and borrows. This is correct, right?

**Comment by Marx-Melencio** [comment]
Yep. This solves the issue. Thanks again, @sakulstra !

**Comment by sakulstra** [comment]
@Marx-Melencio yes, that's how it works :)
