### ISSUE TITLE
Show warning if user cannot afford gas

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#669]
**Is your feature request related to a problem? Please describe.**
A user reported an issue https://github.com/aave/interface/issues/668#issue-1206358863 and eventually it turned out the wallet eth wasn't enough to pay for the transaction gas. While that's obviously not a protocol level issue It would be nice if the ui would be a bit more descriptive in that case.

**Describe the solution you'd like**
If the users `native token balance` is lower¹ then the calculated transaction cost the ui should show an error on the transaction screen.

¹in addition to that it might make sense to also show a warning when the native balance is below a certain threshold as sometimes it happens that people accidentally deposit all their "eth" and then no longer can withdraw without first funding the account trough another source.

**Additional context**
#668

**Comment by gabriel-horvat** [comment]
Hey! I'd like to do this. Seems like a good first issue for someone new to the code base

**Comment by defispartan** [comment]
@MareskoY @bojanaave Could we test this to see what the current behavior is with different transaction modals, and see if we need to update this warning?
