### ISSUE TITLE
Wrapped base assets not available in faucet

### ISSUE THREAD

**Issue by defispartan** [aave/interface#679]
Wrapped base assets can't be fauceted even though they're mintable reserves on testnet

**Comment by sakulstra** [comment]
This was done on purpose as people always deposit but then have issues withdrawing as the tokens are not actually backed(there's no eth that can be unwrapped)

Where does this request come from? Is there any need for the native asset that can't be simulated with another asset?

**Comment by defispartan** [comment]
Was from someone in Discord. Since the fauceted WETH breaks the withdraw I don't think it makes sense to add this either, closing the issue.
