### ISSUE TITLE
Aave v2 to v3 migration

### ISSUE THREAD

**Issue by chriscrutt** [aave/interface#681]
**Migrate Aave v2 positions to Aave v3**

Right now InstaDapp allows you to migrate your Aave v2 position (both deposits and borrows) to v3. The caveat is that you can only do it if you move your positions to their platform/a smart contract. If you wish to withdraw back to your wallet you’re required to pay back all your loans :(

It would be nice if Aave implemented an easy way to migrate positions from v2 to v3 on its website while keeping your assets in your wallet and not having to liquidate/pay back loans.

As a side note, it would also be cool to have a debt swap function if you'd like to swap from one stablecoin to another without repaying loans. I know InstaDapp has a collateral/debt swap function too. For example, swapping USDC loan for DAI.

I also added this to the Aave governance forum [here](https://governance.aave.com/t/aave-v2-to-v3-migration/7834)

**Comment by chriscrutt** [comment]
Should I create another feature request for the debt swap function I mentioned? Or leave it be.

**Comment by sakulstra** [comment]
> Should I create another feature request for the debt swap function I mentioned? Or leave it be.

Would do so yes, it's a quite cool idea and shouldn't be too hard to do.
cc: @foodaka

**Comment by chriscrutt** [comment]
> > Should I create another feature request for the debt swap function I mentioned? Or leave it be.
> 
> Would do so yes, it's a quite cool idea.

posted https://github.com/aave/interface/issues/731 @sakulstra

**Comment by ef3n9r98** [comment]
Hi @chriscrutt, @sakulstra, @drewcook, @defispartan - is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ]([www.openq.dev](http://www.openq.dev/)) to attract devs. 

Thanks!

**Comment by sakulstra** [comment]
@ef3n9r98 this is already being worked on https://github.com/bgd-labs/aave-interface/pull/9

Debtswap as well actually.

**Comment by chriscrutt** [comment]
sweeeeet

**Comment by chriscrutt** [comment]
Hey I just saw then enabled migration on the interface! Shall we mark this as closed?
