### ISSUE TITLE
Show indication to user when the supply, borrow caps, or debt ceiling are reached

### ISSUE THREAD

**Issue by foodaka** [aave/interface#688]
**Is your feature request related to a problem? Please describe.**
The issue is that when either the debt ceiling or the supply or borrow caps is nearly reached, there isnt a warning to the user that the tx may fail because the limits are reached.

![Image Pasted at 2022-4-20 10-43](https://user-images.githubusercontent.com/8342048/164239427-e2a8b088-1305-4afb-9459-349b85649825.png)

**Describe the solution you'd like**
Either in the transaction modal or on the dashboard somewhere, a warning message or indication that because of the supply / borrow caps / debt ceiling is nearly reached, the transaction is likely to fail

**Additional context**
Reported in Aave support
"So I supplied 10k of USDT on Avax, enabled e-mode but can only borrow $7, even though there is 1.7M of liquidity available?"
![Image Pasted at 2022-4-20 10-42](https://user-images.githubusercontent.com/8342048/164239775-c2042a78-d62c-41ee-8444-6dcd263355f3.png)

**Comment by defispartan** [comment]
Changed the title a bit @foodaka 

The app limits the amount you can supply/borrow automatically, so there shouldn't be a case where the tx fails. It's just explaining to users why they can only supply/borrow a limited amount

**Comment by iamanastasia** [comment]
I believe we can look into 3 directions:
1. When caps and ceiling are at 100%
2. 95% (nearly reached, based on amount available, not %).
3. When it's all ok.

**Comment by iamanastasia** [comment]
So the first case — 100% reached. 

I think it's important to highlight limit on Dashboard and Reserve page. Also we should hide assets form the Assets to supply/borrow:
![dashboard — borrow cap 100%](https://user-images.githubusercontent.com/92739089/177983295-a1b843f4-8e68-40f2-bb0d-e03d2272948f.png)
![dashboard — supply cap 100%](https://user-images.githubusercontent.com/92739089/177983302-1bd5c6cd-d5f6-4a6c-8033-c73e5385c067.png)
![reserve — borrow cap 100%](https://user-images.githubusercontent.com/92739089/177983306-0205a4a2-1e15-48b6-96e9-a15e7693297e.png)
![reserve — supply cap 100%](https://user-images.githubusercontent.com/92739089/177983309-af3a66a0-8dcc-4c61-adec-25693f48ac13.png)

**Comment by iamanastasia** [comment]
For the debt ceiling reaching 100% there are few nuances.

1. Should give a transparent message that's it's impossible to borrow against this asset, but technically user can still supply this asset. 
So in the dashboard we change Collat. to dash. And add danger message to tx.
![reserve — debt ceiling 100%](https://user-images.githubusercontent.com/92739089/177983953-9589b30b-bde4-4708-a7e3-8d787524adce.png)
![supply tx — debt ceiling 100%](https://user-images.githubusercontent.com/92739089/177984153-516aa68d-162e-408d-8101-853c30015ffe.png)
![Dashboard — debt ceiling 100% not supplied](https://user-images.githubusercontent.com/92739089/177984158-415922fb-0414-460b-960a-e503ff0acd62.png)

 
 2. If the asset was already supplied — disable collat. handle and provide warning/explanation to it.
![dashboard — supplied debt ceiling 100%](https://user-images.githubusercontent.com/92739089/177984494-0d462d6a-0862-4022-a4f3-4b9a6fb58637.png)
 
 3. When user already borrowed against it — disable borrowing for him 
![dashboard — supplied and borrowed debt ceiling 100%](https://user-images.githubusercontent.com/92739089/177984620-2d53076b-08aa-482f-bedb-624076fca61d.png)

**Comment by iamanastasia** [comment]
Second use case — Supply/borrow caps nearly reached (98% as an example)

1. Need to provide warnings (should we include amount that's available to supply/borrow?)
2. BUT if user budget is less than the cap — don't show the warnings.
![dahsboard — supply cap 98%](https://user-images.githubusercontent.com/92739089/177985007-e6b7e34f-04e9-43f8-9542-667dee1ae21e.png)
![supply tx — supply cap 98%](https://user-images.githubusercontent.com/92739089/177985014-935a3e5a-d4d8-4cf4-8082-4f01d80b5d15.png)
![reserve — supply cap 98%](https://user-images.githubusercontent.com/92739089/177985016-b0166bc8-d172-448a-a7d7-7587482ed77b.png)

**Comment by iamanastasia** [comment]
Case of debt ceiling ~98%
![supply tx — debt ceiling 98%](https://user-images.githubusercontent.com/92739089/177985315-0392a2a2-5a86-4ecd-a2fa-894ac0905e11.png)
![dashboard — debt ceiling 98% (not supplied)](https://user-images.githubusercontent.com/92739089/177985325-8254695a-71b5-4440-b790-bf8b4282ee45.png)
![enable collat tx — debt ceiling 98%](https://user-images.githubusercontent.com/92739089/177985327-169c3064-b34b-44a9-af84-eaec32397cab.png)
![dashboard — debt ceiling 98% (already supplied)](https://user-images.githubusercontent.com/92739089/177985329-51e216f0-aa97-48ff-9010-6cfff17cb269.png)
![borrow tx — debt ceiling 98%](https://user-images.githubusercontent.com/92739089/177985330-5228443b-2206-42c1-af4a-ad02ac1b958e.png)
![reserve — debt ceiling 98%](https://user-images.githubusercontent.com/92739089/177985332-53ae8a25-8d46-43f5-b4af-41d66b4e6d4d.png)

**Comment by iamanastasia** [comment]
And happy case when all limits are good ~40%. Only edge case here is that user want to work with extra large amounts and doesn't fit the limits. 

![reserve — debt ceiling 40%](https://user-images.githubusercontent.com/92739089/177985518-5de513da-330f-4b0c-9a0b-ab287c896964.png)
![reserve — borrow cap 40%](https://user-images.githubusercontent.com/92739089/177985523-4680e9d7-8417-4300-9e89-5d007522f30e.png)
![reserve — supply cap 40%](https://user-images.githubusercontent.com/92739089/177985527-8e190dea-45c0-4986-bdb7-5857e16ae3c4.png)
