### ISSUE TITLE
Align the 'copy the error' font with the error message

### ISSUE THREAD

**Issue by helpfulBro** [aave/interface#692]
**Is your feature request related to a problem? Please describe.**
As per the screenshot the CTA styling is not aligned to the rest of the messaging

**Describe the solution you'd like**
Align the font to match the error copy

**Describe alternatives you've considered**
Perhaps change the CTA to be a button?

**Additional context**
![image](https://user-images.githubusercontent.com/25915621/164349408-f770c8d3-c8b3-40f8-b0a3-fcd64b1b74ae.png)

**Comment by iamanastasia** [comment]
From a design point of view the fix should be the following:
If it is not a button, it is a simple hyperlinked text. Thus text style just matches the rest description and is underlined.

**Comment by defispartan** [comment]
> From a design point of view the fix should be the following: If it is not a button, it is a simple hyperlinked text. Thus text style just matches the rest description and is underlined.

Sounds good, I'll change it throughout the app
