### ISSUE TITLE
Stable rate wrong explanation string and review of another string

### ISSUE THREAD

**Issue by sirsoth** [aave/interface#719]
**Describe the bug**
One string over the UI stands that stable rate stays "fixed" for the duration, which from my understanding is unaccurate as, even unlikely, it can be rebalanced.

**To Reproduce**
Wrong String at #: src/components/infoTooltips/APYTypeTooltip.tsx 
"Allows you to switch between <0>variable</0> and <1>stable</1> interest rates, where variable rate can increase and decrease depending on the amount of liquidity in the reserve, and stable rate will stay the same for the duration of your loan."

I would suggest to be updated to something like: (better to get a review)

"Allows you to switch between <0>variable</0> and <1>stable</1> interest rates, where variable rate can increase and decrease depending on the amount of liquidity in the reserve, and stable rate will stay the same for the duration of your loan unless if it gets rebalanced over extreme conditions"

Another String, that might be fine but just to review:

#: src/components/infoTooltips/EModeTooltip.tsx 

"E-Mode increases your LTV for a selected category of assets up to<0/>. <1>Learn more</1>"

I just want to make sure that the open for that <0/> is somewhere, as it seems its incomplete the string but maybe the '<0>' is opening in another string. Otherwise is missing.

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)

**Comment by drewcook** [comment]
Could be related with #960 where dynamic values are wrapped in `<Trans>`, so just investigating and ensuring that those cases are implemented correctly.

**Comment by sirsoth** [comment]
@drewcook Not sure if there might be any other issue involved, but what Im reporting here is only that its not accurate the statement "stable rate will stay the same for the duration of your loan." as stable rates could be rebalanced

**Comment by grothem** [comment]
Closing this since it's a duplicate, and will be fixed by #1747
