### ISSUE TITLE
Reserve overview improvements

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#720]
**Is your feature request related to a problem? Please describe.**
As a developer & user I want to figure out which token is in a specific reserve.
This is valuable info when doing some research, but also when interacting with 3th party tools which sometimes require the tokenAddress being inserted. This is especially true as some 3th party tools list tokens with the official symbol name (e.g. amUSDC which is not visible anywhere on the ui). E.g. while swapping supplied USDC to AAVE is perfectly possible on paraswap you will have a hard time doing so as you either need the address or need to know the symbol names(when swapping to GHST you actually need the address as the symbol is not listed).

**Describe the solution you'd like**
While there is a link to the oracle & underlying asset, i'd also love to see a link to aToken(on total supplied) and potentially also v & s tokens and stable and variable borrows.
![image](https://user-images.githubusercontent.com/4396533/165556394-a8e98263-955f-4a29-b601-f0b84840889c.png)

Slightly related to https://github.com/aave/interface/issues/685

**Comment by iamanastasia** [comment]
Hey @sakulstra we added a select of aToken, variable and stable borrow tokens to the asset panel. Does it help to solve the problem you mentioned? We can also add option to copy address here. 
<img width="1395" alt="Screenshot 2022-07-08 at 15 05 16" src="https://user-images.githubusercontent.com/92739089/177980759-92e436b0-f91b-4da2-a50c-83b96e41426b.png">
