### ISSUE TITLE
swap ui quirk

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#721]
**Describe the bug**
There's a weird ui quirk when swapping from an asset that has an incentive to one without.

**To Reproduce**
1. Go to any market with incentives
2. Click on swap
3. Swap an asset with incentive to one without

**Expected behavior**
No broken ui

**Screenshots**
![image](https://user-images.githubusercontent.com/4396533/165558742-c3563eb1-5cb3-4ce3-8eb9-e91db4a2b4ce.png)

**Comment by defispartan** [comment]
Will be superseded by collateral swap re-design PR, don't have issue to link yet
