### ISSUE TITLE
Logic for Health factor warning warns in high HF situations

### ISSUE THREAD

**Issue by sirsoth** [aave/interface#722]
**Describe the bug**
In certain situations when the health factor is high, the logic keeps showing a warning of "low health factor" even when HF is above 4 (as in screenshots)

**To Reproduce**
- Replicate position as in screenshot
- Go to dashboard

**Expected behavior**
There should not be warnings when health factor is decently high, maybe just show when its below 1.5 
Or have multiple warnings, depending on the range of HF

**Screenshots**
![image](https://user-images.githubusercontent.com/5862694/165731352-7806c4a7-ef62-46fc-9460-9cc9fd10dcd8.png)

![image](https://user-images.githubusercontent.com/5862694/165731363-b1916d34-1e27-46e6-aa7f-e61428033719.png)

**Comment by defispartan** [comment]
@sirsoth Is this still relevant? There have been a few updates to HF components since this issue was created

**Comment by sirsoth** [comment]
@defispartan might not be, we did not get this reported recently so it might be safe to say it was sorted out in previous updates

**Comment by grothem** [comment]
Closing this, seems to not be an issue anymore
