### ISSUE TITLE
set up Github production environment

### ISSUE THREAD

**Issue by sendra** [aave/interface#723]
Add on the CI flow when releasing to prod, the creation of a Github environment so on the github repo page the link to the app stays updated with latest ipfs release. This will also add release historics.

see for reference:
https://stackoverflow.com/questions/67385568/github-actions-how-to-dynamically-set-environment-url-based-on-deployment-step/67385569#67385569
![image](https://user-images.githubusercontent.com/6848271/165733123-f681643e-8ab1-40cf-a655-e917a838346e.png)

Would also be cool, if possible, if we could also maintain updated versions of the different ipfs gateways, as to ease the entry point just in case cloudflare went down.

**Comment by sakulstra** [comment]
The cool think with this is that github has an api for releases so a simple component could be build to check for the latest production url cip and offer to redirect if there's a mismatch essentially solving https://github.com/aave/interface/issues/711 in a way that does work for potentially any gateway.
