### ISSUE TITLE
"I accept the risk" or risky mode for certain actions

### ISSUE THREAD

**Issue by sirsoth** [aave/interface#726]
**Is your feature request related to a problem? Please describe.**
Not to a problem, but some people wants to bypass certain limits in the UI, for example they would like to be able to withdraw to really low HF levels, for example 1.02 HF

**Describe the solution you'd like**
In my opinion the best way to handle would be, or allowing an option in the action 'I accept the risk of bringing down even lower my HF", or having some kind of "expert/risky mode" in the settings (top right corner)

**Comment by jmbus206** [comment]
I could still withdraw my deposit to repay my debt at very low HFs like 1.4, 1.3 or even 1.2. It still allowed to withdraw certain amounts.
However today it suddenly does not allow any amount at every version of AAVE, ETH Polygon v2 and v3.
It is ridicuous. THere should have been some notice...or announcement about HFs until which that I can withdraw.
Like this I have to wait and see the liquidation

**Comment by defispartan** [comment]
> I could still withdraw my deposit to repay my debt at very low HFs like 1.4, 1.3 or even 1.2. It still allowed to withdraw certain amounts. However today it suddenly does not allow any amount at every version of AAVE, ETH Polygon v2 and v3. It is ridicuous. THere should have been some notice...or announcement about HFs until which that I can withdraw. Like this I have to wait and see the liquidation

Could you share a screenshot? The UI should allow you to withdraw any amount down to a health factor of 1.07, and if you want to withdraw lower you can interact with the contract directly. If this is not the case and you're not able to withdraw at higher HFs then this should be made into a separate issue.
