### ISSUE TITLE
Swapping Borrowed Assets

### ISSUE THREAD

**Issue by chriscrutt** [aave/interface#731]
Right now [Instadapp](https://polygon.instadapp.io/aave-polygon) allows you to swap your existing debt from one collateral type to another within the protocol.

It can be used to refinance debt to achieve a better rate and also used to execute a short position.

The caveat using Intsdapp is that you can only do it if you move your positions to their platform/smart contract. If you wish to withdraw back to your wallet you’re required to pay back all your loans :(

It would be nice if Aave implemented an easy way to swap debt (for example a USDT borrowed position into USDC) on its website for v2 **_and_** v3 while keeping your assets in your wallet and not having to liquidate/pay back loans.

edit: also added to [governance.aave.com](https://governance.aave.com/t/swapping-borrowed-assets/7993)

edit 2: according to [sakulstra](https://governance.aave.com/t/swapping-borrowed-assets/7993/4?u=o_o) it
> should be possible with flashloans + e.g. paraswap which would be very similar to what is currently done for repay with collateral and collateral swap.

**Comment by chriscrutt** [comment]
looks like [0xPilou](https://github.com/0xPilou/DebtFlashSwap) made a smart contract for this kind of thing in 2021

**Comment by chriscrutt** [comment]
@drewcook was there an update? Lol

**Comment by drewcook** [comment]
Hey @chriscrutt - no updates, still an open issue.

**Comment by grothem** [comment]
This feature was added as part of https://github.com/aave/interface/pull/1668
