### ISSUE TITLE
"Switch to Aave Classic" is not visible/clickable over real iOs 

### ISSUE THREAD

**Issue by bojanaave** [aave/interface#741]
**Describe the bug**
When a user opens app.aave.com and then click on the menu in the right upper corner - "Switch to Aave Classic" will not be visible/clickable
**To Reproduce**
1. Go to app.aave.com
2. Click on menu icon in the right upper corner
3. Scroll down till button "Switch to Aave Classic"
4. Observe

**Expected behavior**
Switch to Aave classic button should be visible and clickable.

**Screenshots**

https://user-images.githubusercontent.com/104987757/166926818-1cc6104b-b6a3-4023-bf5d-bc2d2bbbbe07.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone 11 pro max
 - OS: 15.4.1
 - Browser : Safari

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)

**Comment by defispartan** [comment]
Still an issue with Safari on iOS

**Comment by drewcook** [comment]
Confirmed this works on Brave mobile browser on an iPhone12, so definitely a quirk with Safari.

**Comment by defispartan** [comment]
Made irrelevant by #1063
