### ISSUE TITLE
Voters list

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#744]
**Is your feature request related to a problem? Please describe.**
On the classic ui there was a feature on proposals that allowed to show lists of participants (top 10 for and against).
I'm not a huge fan of limiting the list to top 10, but it would be nice to have that list again.

**Describe the solution you'd like**
A list of participants with their respective vote & link to their etherscan.

**Additional context**
The votes are already cached & i'm pretty sure there's already a utility somewhere to fetch new votes clientside, so the only missing piece is a ui to show them.

**Comment by iamanastasia** [comment]
Here is design how it might look like. 

1. Proposal page contains framed section with Top 10 addresses sorted by the amount of votes.
![Main view](https://user-images.githubusercontent.com/92739089/194038683-f8f20c68-6713-4f99-ae3b-e016dbaec258.png)



2. If there are more than 10 addresses then there is a button to view full list in modal window.
![Full list modal window](https://user-images.githubusercontent.com/92739089/194038754-793a175d-326e-4c81-8a3b-e026f9a14821.png)

3. And for mobile view we need to add tabs (both — for page and modal window)
![Mobile modal window](https://user-images.githubusercontent.com/92739089/194039080-443d2bdb-9107-4c28-8ab6-baa90e18502a.png)
![Mobile view](https://user-images.githubusercontent.com/92739089/194039086-84f39e3e-9601-436d-a59f-0043e5ef2e28.png)
