### ISSUE TITLE
Add spacing before FAQ on the Approval modal

### ISSUE THREAD

**Issue by bojanaave** [aave/interface#746]
**Describe the bug**
When a user clicks on the "i" and Apporaval modal is opened spacing is missing before FAQ word.

**To Reproduce**
1. Go to app.aave.com and enable testnet mode
2. Click on the Dashboard
3. In section "Assets to supply" click on the any token that you have - enter some amount in the "Supply <token>" modal
4. Click on the "i" next to "Why do I need to approve?" 

**Expected behavior**
We should add space between our and FAQ words.

**Screenshots**
<img width="1131" alt="Screenshot 2022-05-06 at 09 29 36" src="https://user-images.githubusercontent.com/104987757/167087187-2a65498a-ce9e-42da-bc7f-d19c7eab3501.png">

**Desktop (please complete the following information):**
 - macOS (Big Sur)
 - FF/Chrome/Safari/Brave

**Smartphone (please complete the following information):**
 - iOS (Iphone 11 Pro Max)
  - Safari / (Browser through metamask)
  - iOS 15.4.1

**Comment by MatthewCYLau** [comment]
Raised a new PR to fix this issue since the old fix PR is stale.
