### ISSUE TITLE
[BUG] Percentages are not visible when a user switches between stable and variable on real mobile device

### ISSUE THREAD

**Issue by bojanaave** [aave/interface#747]
**Describe the bug**
Percentages are not visible on real mobile device when a user switches between stable and variable

**To Reproduce**
1.  Go to app.aave.com and enable testnet mode (over mobile) 
2. Click on the Dashboard
3. And click on the borrow token that I want e.g USDC 

**Expected behavior**
When a user switches between stable and variable percentage of the select option is not visible
**Screenshot**

https://user-images.githubusercontent.com/104987757/167089215-0e0661e7-78d2-4d00-b8d2-0f7256f3fe76.MP4

ts**

**Smartphone (please complete the following information):**
Iphone 11 Pro Max
iOS 15.4.1 
Browser opened through Metamask

**Comment by foodaka** [comment]
could not reproduce on browser or on my mobile device with samgsung s10e, @MareskoY can you check and if we can reproduce we can reopen
