### ISSUE TITLE
Make the wording inside "Back" button to be the  same across Aave application

### ISSUE THREAD

**Issue by bojanaave** [aave/interface#774]
**Is your feature request related to a problem? Please describe.**
On some pages (such as Markets/Dashboard) wording inside back button is " <- Go Back " while on some pages (Governance - Updates ) it says "<- back" 

**Describe the solution you'd like**
Would be great to have the same wording inside back buttons across the whole Aave application

<img width="933" alt="Screenshot 2022-05-13 at 09 59 44" src="https://user-images.githubusercontent.com/104987757/168239313-cb531701-2d39-45d2-8a08-4a072f52d3b5.png">

Note: the same "problem" is visible over Desktop (all browsers)

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)
