### ISSUE TITLE
Rounding error causing transactions to fail when supplying coins

### ISSUE THREAD

**Issue by stephenjust** [aave/interface#780]
**Describe the bug**
When attempting to supply all of a wallet's USDC to AAVE's polygon network, the transaction fails.
The UI supplies error text "Internal JSON-RPC error."

**To Reproduce**
1. Go to 'AAVE Polygon USDC market'
2. Click on 'Supply'
3. Select "Max"
4. Send transaction
5. Observe transaction failure.

**Expected behavior**
The transaction should succeed with all coins from the wallet.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] 101

**Additional context**
The transaction succeeded after I manually reduced the transaction size by 0.1 coins. My assumption is that there is a rounding mismatch happening somewhere.

**Comment by fankeu** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into.

**Comment by sakulstra** [comment]
@stephenjust are you in polygon v3 or v2? That info will help debugging as the "max" works different between the versions.

**Comment by stephenjust** [comment]
I'm using polygon V2.

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)

**Comment by grothem** [comment]
Closing this, seems like it's not an issue anymore.
