### ISSUE TITLE
Aave supply not working on trust wallet

### ISSUE THREAD

**Issue by Nielsbishere** [aave/interface#790]
**Describe the bug**
When I go to Aave Arbitrum using trustwallet I have to put in supply to borrow first.
This requires me to approve moving of USDC to Aave. When I do, Aave is closed in trustwallet and when I go back, it will go back to the screen and doesn't know I hit approve. Meaning that with Trustwallet, Aave is completely unusable.

**To Reproduce**
1. Get Trustwallet
2. Go to Aave supply on Arbitrum
3. Try to supply some USDC
4. Hit approve; you can't do it without being kicked back to the main screen.

**Expected behavior**
Expected to allow me deposit USDC so I can borrow something.

**Screenshots**
N.A.

**Smartphone (please complete the following information):**
 - Device: Note 9
 - OS: Android 10
 - Browser: Trustwallet
 - Version: Latest

**Additional context**
N.A.

**Comment by bojanaave** [comment]
Hi I can not reproduce reported problem on iPhone 11 pro Max (iOS 15.4.1) - Trust wallet (7.4 (630)) 
Example video:
https://user-images.githubusercontent.com/104987757/169275718-dd70ce48-ee6b-42dc-b089-49b9925d8d41.mov
 cc @foodaka

**Comment by foodaka** [comment]
@Nielsbishere as per QA we were not able to reproduce. Will close out for now if something else comes up that we are missing feel free to reopen the issue

**Comment by Nielsbishere** [comment]
Here you can see my experience @foodaka:
https://youtu.be/rPoNXnh54_8
The black screen is me putting in my pass and the white boxes are just blocking balances for privacy.
The following happens:
- I go to Aave using the trustwallet browser.
- It correctly shows my address and assets.
- I click supply and input max amount.
- Approve and continue closes Aave.
- I go back to Aave.
- It shows me the asset with the approving message in the button. Due to trustwallet auto refreshing it disappears.
- I try it again and this time it shows me an approve message that I have to sign.
- When I approved it, Aave is gone again.
This always happens and I've not been able to circumvent this.
