### ISSUE TITLE
Add Reserve factor and Interest model variables as a part of risk params

### ISSUE THREAD

**Issue by iamanastasia** [aave/interface#791]
description coming soon...

**Comment by sirsoth** [comment]
Type of update: Improvement (not a bug)
Reasoning: Add more information that is available on-chain (can be fetched directly from the contracts) as its not possible/worth to be constantly and manually updating in docs these parameters, as governance can update these ones easily time to time (there are AIPs updating parameters nearly every week)

Information to add:

- Reserve factor: Can be fetched using https://docs.aave.com/developers/core-contracts/aaveprotocoldataprovider (we are already fetching some of those)

- Interest rate parameters, I would add in specific:
-- Base
-- Slope 1
-- Slope 2
-- U optimal
From my understanding these can be fetched from the interest rate strategy address of each asset:
https://docs.aave.com/developers/core-contracts/aaveprotocoldataprovider#getinterestratestrategyaddress 


I would add them at:

Reserve factor: After liquidation penalty
![image](https://user-images.githubusercontent.com/5862694/169279677-13c8f4ad-069e-489a-81c0-fdf3dd0e94eb.png)

Interest rate parameters: below the interest rate chart
![image](https://user-images.githubusercontent.com/5862694/169280183-f2450082-5ac4-4ee9-ba23-0bbb808eb7d5.png)
