### ISSUE TITLE
Governance section not responding when entering an AIP

### ISSUE THREAD

**Issue by sirsoth** [aave/interface#802]
**Describe the bug**
A clear and concise description of what the bug is, including the exact market(e.g. polygon v3) on which it was observed.

**To Reproduce**
1. Go to governance tab at app.aave.com
2. Click on any AIP, for example number 60
3. It will take ton of time to load, and eventually (some times) give an error, for example I got this one for AIP 60 (URL
https://app.aave.com/governance/proposal/60/ )
ipfs resolve -r /ipns/app.aave.com/governance/proposal/60/: error traversing node at "governance/proposal": could not load link "bafybeiaejyr5szqsqvntcj2n4dendhsopojxjqroqwfp4qf5rp3nf3ssja": context deadline exceeded

**Expected behavior**
Load the AIP information and details

**Screenshots**

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/5862694/170023437-f97ca94c-c1b1-4e5a-bb99-9425963facea.png">

**Desktop (please complete the following information):**
Mac os, chrome

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)

**Comment by foodaka** [comment]
This is an issue with cloudflare and ipfs
