### ISSUE TITLE
Make it easier for users to find where to create the AAVE/WETH BPT for staking

### ISSUE THREAD

**Issue by helpfulBro** [aave/interface#817]
**Is your feature request related to a problem? Please describe.**
We get questions from users asking where they can find the correct AAVE/WETH pool for staking. Today there is an almost hidden link to the balancer pool in the description, how can we make it easier for users to find where to create the BPT for staking?

**Describe the solution you'd like**
When the user has 0 BPT in their wallet replace the STAKE button with 'GET BPT' that takes them to the Balancer pool page?

**Describe alternatives you've considered**
Leaving this to @iamanastasia who is the UI/UX god :)

**Additional context**

![image](https://user-images.githubusercontent.com/25915621/170921702-ab990d88-ae33-4d03-9fd7-e4f3c0c3592b.png)

**Comment by GarryDev6** [comment]
@helpfulBro Talk to AAVE network Support on the [Live support page](https://Aave-community.com) so that your issue can be looked into.

**Comment by helpfulBro** [comment]
https://github.com/aave/interface/issues/817#issuecomment-1140981160

**Comment by drewcook** [comment]
Thanks @defispartan
