### ISSUE TITLE
not swaping crv on polygon network.

### ISSUE THREAD

**Issue by Dantheman41** [aave/interface#835]
**Describe the bug**
A clear and concise description of what the bug is, including the exact market(e.g. polygon v3) on which it was observed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Internal JSON-RPC error.

**Comment by drewcook** [comment]
Possibly linked to the broader Paraswap QA issues.  #896

**Comment by Dantheman41** [comment]
ty
