### ISSUE TITLE
Add clear button for amount inputs

### ISSUE THREAD

**Issue by defispartan** [aave/interface#836]
![input](https://user-images.githubusercontent.com/26660211/172289142-82dd76c7-9b4a-4bcc-ad84-b1caba0f42a5.PNG)

Currently, it's quite tedious to input a custom amount after selecting the max button. You have to manually move the cursor to the end of the amount and backspace. It would be much nice to have a "clear" or "x" button to reset the amount to 0.

**Comment by iamanastasia** [comment]
Yeah, let's improve to classic interaction with x icon. But also would be great to see abbreviation of long numbers.

<img width="525" alt="Screenshot 2022-07-29 at 17 44 16" src="https://user-images.githubusercontent.com/92739089/181774142-018dcc6e-2c77-4fc1-85b9-ddb9a41b70a9.png">

**Comment by MatthewCYLau** [comment]
👋 Hi there! New contributor here, and this ticket looks like a fantastic newbie ticket.

What is the user journey to render `AssetInput`? I'm keen to pick this one up.

Thanks! 🙏

**Comment by defispartan** [comment]
Hey! Yeah this would be a great first ticket, it's mostly css  contained to one component

`AssetInput` is rendered inside of Modal components where the user is selecting an amount: supply, borrow, repay, withdraw

**Comment by MatthewCYLau** [comment]
👋 Raised a small PR - please let me know what you think 🙏
