### ISSUE TITLE
Stacking Enhancements

### ISSUE THREAD

**Issue by varma61923** [aave/interface#845]
Add Stacking support for multiple coins Bitcoin, Polygon, Flow, SOL or add stacking support to ERC-20 tokens. Also please consider adding liquidity stacking for the same.

Thanks & Regards
Pavan

**Comment by defispartan** [comment]
This repo only contains frontend interface for the protocol. Listing new assets (including staked versions of assets) is done through [Aave Governance](https://governance.aave.com/). 

The full process is explained [here](https://docs.aave.com/developers/guides/governance-guide/)
