### ISSUE TITLE
Add a simulation mode into the Aave App

### ISSUE THREAD

**Issue by foodaka** [aave/interface#850]
**Is your feature request related to a problem? Please describe.**
One feature some other protocols have is a simulation mode. This is a good way to onboard new users to try out how the application works without overhead

**Describe the solution you'd like**
- Add a simulation mode that works like main net fork for 30minutes.
- Seed the users wallet with tokens

**Comment by drewcook** [comment]
This is a good feature to include and plan.  But this could be researched more with #1034 - so closing for now.
