### ISSUE TITLE
Ethereum Ropsten V3

### ISSUE THREAD

**Issue by tretonis** [aave/interface#860]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tretonis** [comment]
Regarding the Aave protocol

We are working on the development of a contract involving flash loan.

Question : Where is the Provider and Tokens address
For the Ethrereum Ropsten v3 test?

Thanks

**Comment by defispartan** [comment]
You can find the addresses [here](https://github.com/aave/docs-v3/commit/470dec44bd595f9777bd3c4ba4e94d7015fab053). Looks like there was an issue syncing these to Gitbook, I'll check on this.

PoolAddressesProvider: 0x303a4B174663A6201Da77782413B4b54EFa3E97e

AAVE: 0xa17669420eD99FAc51308567B08B7BaC86837BAf
DAI: 0x85b3362A4c46D57B77844cD64480657bA8D24c8C
EURS: 0xF48271dC38dC811CD7CE2720192e9E8aCd180C03
LINK: 0xE7f01aFb875ad81F11E65fF256bB316Cc5fafFc0
USDC: 0xe99F86Ec081BcA8b1627BDf8062C19fAcC79997B
USDT: 0xAf5a1D0523cF9E38005E234a9eea82cc167CC474
WBTC: 0x1a57E7d60bAEFf506634ef69920aaA5de35Dea47
WETH: 0x7066EE910f85F3a4A4976670a349D7FE617ED8f5

**Comment by foodaka** [comment]
Closing as a discussion and not an issue related to the repository.
