### ISSUE TITLE
Investigate why coinbase wallet browser extension does not work on Aave app

### ISSUE THREAD

**Issue by bojanaave** [aave/interface#865]
**To Reproduce**
1. https://www.coinbase.com/wallet (add coinbase wallet as extension to your Chrome web browser)
2. Open Aave app -> switch to testnet mode
3.  Try to supply / borrow/ faucet assets

**Expected behavior**
As a user who uses coinbase wallet I should be able to interact with aave app.

**Screenshots**

https://user-images.githubusercontent.com/104987757/173309281-572594bf-54bd-4e50-b8f8-fa54652c0915.mov

**Desktop (please complete the following information):**
macOS
Chrome (latest)

**Comment by grothem** [comment]
FWIW I tried connecting to uniswap and curve using Coinbase, and I got this same error

**Comment by grothem** [comment]
This seems to be working for me now. I wonder if they were having issues with their RPC.

**Comment by bojanaave** [comment]
@grothem I can still reproduce the issue with coinbase.

https://user-images.githubusercontent.com/104987757/174037197-38a70ea8-554c-4cf3-a0b2-20647ebda948.mov

**Comment by grothem** [comment]
@bojanaave and I were looking at this, seems like it's a geographic restriction on the Coinbase side. The extension makes a call to their api endpoint, `checkGeoAvailability` before showing the transaction to confirm/cancel.

**Comment by bojanaave** [comment]
You were right @grothem  , we can close this ticket.
