### ISSUE TITLE
Swap throwing client exception error when tx failed 

### ISSUE THREAD

**Issue by foodaka** [aave/interface#866]
**Describe the bug**
When swapping from WBTC to WETH on polygon market V2 the transaction failed and crashed the application. The error thrown was `Cannot read properties of undefined (reading underlyingBalance)`

**To Reproduce**
1. Go to polygon v2 market
2. Swap WBTC to WETH

![Image Pasted at 2022-6-13 12-02](https://user-images.githubusercontent.com/8342048/173341936-634b6ffd-93f5-4481-bb76-f0ac8c3512f6.png)

**Comment by foodaka** [comment]
Possibly related to https://github.com/aave/interface/issues/835

**Comment by drewcook** [comment]
Related to #700 - app level error that crashes it, so it makes sense to fix this with the error screen.
