### ISSUE TITLE
Connecting using Frame does not work

### ISSUE THREAD

**Issue by bojanaave** [aave/interface#878]
**Describe the bug**
When a user lands on the app.aave.com page user must connect his wallet with app, but if a user choose to connect using Frame nothing will happen
**To Reproduce**
1. Go to app.aave.com
2. Click on Connect Wallet button 
3. Click on the "Frame" inside "Connect a Wallet" modal

**Expected behavior**
Users must be able to connect their Frame wallets

**Screenshots**
![Screen Shot 2022-06-15 at 14 10 46](https://user-images.githubusercontent.com/104987757/173823905-3ba52f45-ad39-4edb-9ef9-5b12a301898a.png)

**Desktop (please complete the following information):**
macOS 
Chrome/Brave/Firefox

**Comment by defispartan** [comment]
@grothem Could you try testing this on mac tomorrow? On both Windows and Linux it's working for me on all browsers. 

On first connect I had to accept the connection request from the Frame desktop app. @bojanaave is there any request or error inside of Frame when the connection fails?

**Comment by grothem** [comment]
It's not working for me on Mac. It's just rejecting the connection immediately, I don't get a request from the desktop app. I got the same result when I tried it on Curve too.

**Comment by grothem** [comment]
Ok I got it to work now on Mac. After I installed the desktop app, I didn't have a signer selected. I set one up, and now I get the request to connect now.
