### ISSUE TITLE
Not Showing Tokens in the Borrowing List

### ISSUE THREAD

**Issue by mohsen13701** [aave/interface#879]
### I faced a problem while I was trying to borrow $usdc against my collateral of stETH on mainnet. I noticed that there are no tokens in the borrowing list. I thought it could be because of the small size of my collateral (<0.01$), but when I switched to Classic Aave I was able to borrow $usdc. I don't know exactly what the problem is, but after asking from aave discord support we thought it could be related to the user interface, not protocol. 
I also provide a screenshot of the problem here.**
![unknown](https://user-images.githubusercontent.com/90992596/174230497-6c4704b3-0453-45ee-afc8-d07babc55ca0.png)

**Comment by supportactivator** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue https://direct.lc.chat/14234769

**Comment by defispartan** [comment]
This is likely just caused by rounding. If you really want to borrow against this collateral amount you can call borrow on the Pool contract directly (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9) and input any amount as low as 1/10^18
