### ISSUE TITLE
Add route to check wallet address positions

### ISSUE THREAD

**Issue by foodaka** [aave/interface#880]
**Is your feature request related to a problem? Please describe.**
Right now users can set a mockWalletAddress from inserting into the browser console. This is a bit too technical for some users. A better ux is to allow users to insert a wallet address into the URL and it displays that wallet data. 

**Describe the solution you'd like**
- Users should be able to insert a wallet address into the url and get the wallet position shown in the app - similar to how we do it for mockWalletAddress. So for example when I enter https://app.aave.com/account=WALLET_ADDRESS it should should the dashboard and the positions of this address

**Comment by supportactivator** [comment]
Hello,How may I help you today

**Comment by foodaka** [comment]
Duplicate of https://github.com/aave/interface/issues/578
