### ISSUE TITLE
Approving Maker through Metamask does not work

### ISSUE THREAD

**Issue by Zerophase** [aave/interface#886]
**Describe the bug**
Clicking the approve token button just makes Metamask load the gas transaction approval infinitly. Other tokens work perfectly fine.

**To Reproduce**
1. Put Maker in a wallet.
2. Input amount of Maker to lend.
3. Click "Approve to continue"
4. Watch Metamask never load the transaction approval.

**Expected behavior**
Transaction approval loads, and you can edit the gas fee before confirming.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave and Firefox
 - Version: latest on date of report.

**Comment by defispartan** [comment]
I think this is related to #724. To prevent front-running of approvals, certain tokens have a condition where if they have been previously approved, the approval must be set back to 0 before you can set a new approval.

What you can do is go to the MKR token contract (0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2) and under the write contract tab call the `approve` function with the V2 LendingPool as the spender (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9) and the amount to 0. Then you should be able to set a new approval from the Aave app.
