### ISSUE TITLE
Improve messaging about swap/repay with collateral features

### ISSUE THREAD

**Issue by sirsoth** [aave/interface#898]
**Is your feature request related to a problem? Please describe.**
Current message its wrongly understood as the feature is not working, we might want to improve the warning message to just inform that some pairs or routes might not be optimal.

**Describe the solution you'd like**
Adapt the message to sound less "problematic". Or even if the problems around the features got reduced it might be possible to just remove the warning by now.

**Describe alternatives you've considered**
Improve warning message or remove it if considered

**Additional context**
Screenshot of current message shown

![image](https://user-images.githubusercontent.com/5862694/176147147-bf75d5a7-243c-4447-9734-caf5598e147f.png)

**Comment by foodaka** [comment]
Agree as we have made further improvements on this, we can now update this messaging
