### ISSUE TITLE
stable rate on api seems to be broken & api seems to be stuck on 31.01

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#90]
The code for generating the data is hosted here:
https://github.com/aave/aave-api/blob/master/src/services/RatesHistory.ts#L105

For utilization variable & stable rate the the data seems to be correct (except for ampl, which is a subgraph error). For stable borrow rate it's broken.

You can check on https://app.aave.com/#/reserve-overview/0x0000000000085d4780b73119b644ae5ecd22b376-0x0000000000085d4780b73119b644ae5ecd22b3760xb53c1a33016b2dc2ff3653530bff1848a515c8c5 (stable tusd on mainnet)
In theory stable should move very similar to variable, just at a higher level.

The stableBorrowRate is a bit different then the other rates as it's not based on indexes. So instead of calculating the rate we simply take a snapshot ever x seconds.

The reasons on why this could be broken:
- we don't persists the correct stableBorrowRate in RateHistoryItems, so the underlying data is wrong
- we do persists it, but the api has some bug
- ...?

---

One way to perhaps fix this would be to calculate the stable rate based on utilization instead of taking it from the subgraph? Idk, would still be nice to figure out why it's currently broken.

**Comment by defispartan** [comment]
Issue resides on the subgraph / API / and potentially on the contract level, so there's not much to be done on the interface side
