### ISSUE TITLE
Buttons Version 2 and Version 3 does not work as expected

### ISSUE THREAD

**Issue by bojanaave** [aave/interface#910]
**Describe the bug**
If a user double click on the "Version 3 " or "Version 2" user will get mixed V2 and V3 markets

**To Reproduce**
1. Open app.aave.com 
2.  Open Dashboard and click on the name of your market
3.  Double click on the Version 3 / or on the Version 2 button
4. Observe

**Expected behavior**
Markets should not be unselected if a user clicks twice on the version

**Screenshots**

https://user-images.githubusercontent.com/104987757/176875220-b65e0172-22de-4e9b-8d65-db2e24d38afb.mov

**Desktop (please complete the following information):**
mac OS 

**Additional context**

**Comment by ethabhijit** [comment]
@grothem Can I work on this issue?

**Comment by grothem** [comment]
@ethabhijit I've already got a PR up for this. Thanks though
