### ISSUE TITLE
Improve E-Mode Menu UX

### ISSUE THREAD

**Issue by defispartan** [aave/interface#921]
With the AVAX market now supporting two eModes (stablecoins and AVAX), the menu UX is a bit strange now, especially when selecting for the first time:

![multi-emode](https://user-images.githubusercontent.com/26660211/177434221-7a6e146b-a333-4a25-ae4b-96442b30852c.PNG)

- [ ] "E-Mode Disabled" should not be a menu option when no eMode is active

- [ ] Change the "E-Mode Disabled" text to "Disable E-Mode", and potentially separate switch and disable e-Mode menus

**Comment by vishesh0123** [comment]
can you assign this to me  , I want to work on this ..

**Comment by defispartan** [comment]
> can you assign this to me , I want to work on this ..

Sure thing 👍

**Comment by vishesh0123** [comment]
#943 please review this and tell me if any changes to be done
