### ISSUE TITLE
Harmony - borrow notification, broke UI

### ISSUE THREAD

**Issue by MareskoY** [aave/interface#936]
For desktop version 
<img width="643" alt="Screenshot 2022-07-13 at 13 50 24" src="https://user-images.githubusercontent.com/18032275/178738109-2d021b02-c185-436d-8084-39bd709d1f27.png">

For tablet
<img width="874" alt="Screenshot 2022-07-13 at 13 50 35" src="https://user-images.githubusercontent.com/18032275/178738119-ab6c2889-0c65-4079-b5a4-631e39cc70c7.png">

For Mobile
<img width="512" alt="Screenshot 2022-07-13 at 13 50 46" src="https://user-images.githubusercontent.com/18032275/178738147-29b5eeaa-1d41-4ddf-9a48-9be279f16d64.png">

a warning message should be upper then total blocks/tags:
- Balance $0.10
- APY 0.03%
- Borrow power used 7.67%

**Comment by defispartan** [comment]
Fixed in #934
