### ISSUE TITLE
Make it clear when currently a mock address is used

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#941]
**Is your feature request related to a problem? Please describe.**
When you mock a wallet via `mockWalletAddress` localStorage nowhere on the ui it shows that you're on a mocked wallet leading to confusion quite frequently (when ppl mocked a wallet & forgot when they later check the app again).

**Describe the solution you'd like**
It would be nice if:
- there was a highlighting when your current address is a mocked address
- (optional) it would be nice if you could exit the mock without manually altering storage
- (optional) it would be nice if you could mock without tinkering with the console (a feature in ui)
  - would be cool if on top it would recommend a address which has some funds on all networks/the current network so it's easier to get an impression as sort of "demo" mode

**Comment by foodaka** [comment]
related https://github.com/aave/interface/issues/880

**Comment by foodaka** [comment]
i feel we should remove this mockWallet flow to add it to a route so its more clear, maybe we could also add something to the UI wdyt @iamanastasia

**Comment by sakulstra** [comment]
@foodaka sorry did miss that linked issue.

I feel the "mocking" has some advantages over a seperate position  `url` flow because you can actually "experience" the app in a demo mode without having any assets. Also it helps with debugging quite a bit. As a more advanced user in combination with forks, you can actually impersonate a given user and play around with certain features. Imo that's more powerful/useful then a dedicated page that just allows you to see positions.

In fact there already is a url flow by attaching `?mockWalletAddress=` to the url (iirc it just sets local storage under the hood).

---

I agree though that this feature needs to be more prominent and user friendly as manually setting url parameters or localStorage is not really usable for most ppl.

**Comment by foodaka** [comment]
I think on the classic we had that flow in the url, now it is not there. We can still have the insert into local storage for debugging but for the general user who just wants to mock an address its better from the route for simplicity

**Comment by sakulstra** [comment]
You think setting an url for which you need to know the exact parameter and manually alter the url is easier then a ui integration? Probably i misunderstood, but if not I highly disagree.

**Comment by foodaka** [comment]
I said setting the url is easier than setting in local storage(for route sharing as you mentioned). Setting in the UI somewhere would be best

**Comment by defispartan** [comment]
@sakulstra Here is a concept for adding to the UI: #578 

There's a still a few outstanding questions if you want continue the conversation there
