### ISSUE TITLE
Add ability to see transaction history of a user

### ISSUE THREAD

**Issue by foodaka** [aave/interface#948]
**Is your feature request related to a problem? Please describe.**
Previously in the classic UI we had a way to see users history interacting with the protocol. This was useful in the case of liquidations as users could visually see what happened to their position.

**Describe the solution you'd like**
We should have a history page or tab within the dashboard that users can interact with to see the history of tx across the protocol. This should also be available for institutions and permissioned networks

**Comment by grothem** [comment]
Added as part of https://github.com/aave/interface/pull/1538
