### ISSUE TITLE
Remove caching service

### ISSUE THREAD

**Issue by sakulstra** [aave/interface#951]
**Is your feature request related to a problem? Please describe.**
The caching service was introduced a while ago to workaround limitations of public rpcs, but hasn't been properly maintained (it only supports v2 and staking) and therefore isn't very useful any more.

**Describe the solution you'd like**
Is should be gradually dropped from:
- [x] staking
- [ ] avalanche v2
- [ ] polygon v2
- [x] mainnet v2

When all of these are removed there's no longer any need for graphql on the client which will allow the app to shrink by ~100kb.

**Comment by defispartan** [comment]
V2 in #971 
V2 AMM in #972

**Comment by defispartan** [comment]
Removed completely in zustand PR
