### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rocasx** [aave/interface#952]
I have a question that I would love for you to answer. Where did the data [here](https://cache-api-1.aave.com/graphql) come from? Whether the data here comes from a smart contract or a third-party database. Can you explain the principle to me? Or give me some blogs or papers to study.
Thanks for reading and looking forward to your reply

**Comment by defispartan** [comment]
This endpoint is a caching server (https://github.com/aave/aave-ui-caching-server/), which calls to the UiPoolDataProvider smart contract, then caches it in a Redis store, and exposes a GraphQL endpoint. 

Currently, this is only set up for V2 markets and it's being investigated to deprecate this service #951 and query smart contracts directly on all markets.
